- lib/simple_config.py
> change two tabs to sets of four spaces #spacesbetterthantabs

- lib/simple_config.py
> Revert "change two tabs to sets of four spaces #spacesbetterthantabs"

- lib/network.py
> Add bcc.arihanc.com server

- lib/transaction.py
Solution found by dabura667 in #6
> fix for multisig redeemscript

- lib/bitcoin.py
> Stop downloading legacy headers

- plugins/trezor/plugin.py
This patch contains the minimal changes to get electron cash running with Trezor (firmware 1.5.1).  The patches are cherry-picked from Saleem Rashid's electrum-cash branch.
> Trezor support

- gui/qt/main_window.py
- gui/qt/transaction_dialog.py
Should fix #7 for offline transactions.
> embed input values into tx file for offline signing

- lib/network.py
> Add electron.coinucopia.io server

- electron-cash
- electron.desktop
- gui/kivy/main_window.py
- gui/kivy/tools/bitcoin_intent.xml
- gui/qt/main_window.py
- gui/qt/paytoedit.py
- lib/commands.py
- lib/paymentrequest.py
- lib/tests/test_util.py
- lib/util.py
- lib/wallet.py
- lib/www/index.html
- plugins/trustedcoin/qt.py
… detecting payment uri in "Pay To" field of Send Tab, when scanning qr codes and more places (probably not complete). Fixing fyookball/electrum#23
> use bitcoincash: prefix for URIs (create, parse, scan,..), more string renaming

- gui/kivy/uix/ui_screens/about.kv
Need to fix this before release.
> Change About page on Android ui.

- lib/network.py
> Add server

- lib/transaction.py
- plugins/digitalbitbox/digitalbitbox.py
> digitalbitbox: fix signature hashtype

- gui/qt/__init__.py
See https://github.com/spesmilo/electrum/pull/2820.
> fix Qt threading issue

- .travis.yml
- MANIFEST.in
- lib/tests/test_simple_config.py
- lib/tests/test_transaction.py
This PR repairs tox and travis integration. Travis reports of my repo are here: https://travis-ci.org/Danconnolly/electroncash
1. Removed locale from travis tests, this needs more work.
2. Fixed the user_config test, this was probably just a typo.
3. Refactored the Transaction class tests to support many test transactions, split the tests into smaller tests that verify specific functionality.
Tests for signing transactions not implemented in this PR. This is a problem that needs to be fixed by its own PR.
Tests can be run locally by executing `tox` in the project directory, assuming `pip install tox`.
> Fix Tests and Travis Integration

- gui/kivy/uix/screens.py
- gui/qt/history_list.py
- lib/transaction.py
- lib/wallet.py
fixes #191 
Once I was done with the change in the main area, I realized it might affect the offset of anywhere we use that returned status, so I made the proper adjustments.
> Removed references to RBF in this workflow

- lib/network.py
The hostname / ports don't match what I'm running / what I sent you via reddit-- this should be the correct server info
> Fix dragon.zone server definition

- lib/transaction.py
fixes https://github.com/fyookball/electrum/issues/166
Merging this would make 8c4f3ad3c943b6a39b21744f89d7652d479f6f05 (and related) redundant.
Note that versions with this patch, won't be able to sign unsigned transactions created with older versions; and older versions won't be able to sign unsigned transactions created with this patch; hence you need to upgrade to use this patch on both your online and offline machine (or cosigners) at the same time.
**There is no standard** for unsigned transaction serialization. Chances are you couldn't sign unsigned txs created with Electron Cash using other tools, with or without this patch.
This is a very similar approach to what has been done in Electrum.
https://github.com/spesmilo/electrum/blob/8be777e8825b0f8c5892dcfa863a9868be96d64e/lib/trans …
> tx serialization: encode input amount(value) into unsigned transactions

- gui/qt/main_window.py
- lib/currencies.json
- lib/exchange_rate.py
Added support for CoinFloor public API ticker call for GBP fiat FX
> Added support for several exchanges and fiat currencies, also small fix for default history export filename

- lib/cashaddr.py
- lib/tests/test_cashaddrenc.py
Fix a couple bugs, add more sanity checks, and additional tests.
@kyuupichan @fyookball
> Fix CashAddr size encoding and decoding

- README.rst
- contrib/fix_libs_osx.sh
- Updated contrib/fix_libs_osx.sh to do more stuff automatically
- Updated README.rst to better instruct the user on what to do to build it.
At this point it's more idiotproof -- so you don't need me as much to build it! :)
> Fixups and better instructions for building on Mac OS

- plugins/ledger/ledger.py
- plugins/ledger/qt.py
Fixes #434 
From [spesmilo/electrum #3538](https://github.com/spesmilo/electrum/pull/3538)
> Add ability to show a receiving address on ledger screen 

- gui/qt/main_window.py
Prevents electron cash from crashing when canceling a private key export. This error was caused when the window closed, but a thread continued to try to write to it.
Special thanks to @rt121212121 for helping me fix this one
Fixes #429
> Fix crash when exporting private keys

- pubkeys/README.md
Instructions for verifying file hashes and gpg signatures
> Pubkeys README.md

- plugins/ledger/README.md
Instructions for connecting and troubleshooting Ledger devices with Electron-Cash
> Create Ledger README.md

- lib/keystore.py
- lib/wallet.py
Tested, works.  Has 0 side-effects other than fixing #470.  I recommend merging.
Taken from a fix proposed here: 
https://github.com/goblin/electrum/commit/a3db80c64831b46e255c0fc530f14322530a2b2e
> Updated fix for #470 (tx signing issues).  Now using kyuupichan's advice to pass the sequence number from the wallet down

- lib/commands.py
- lib/wallet.py
Maintains fix for #488, but allows qt to view requests again.
> Fix payment request

- electron-cash
- gui/qt/main_window.py
This probably doesn't warrant a PR, but it's been bugging me a bit.
> Small fixes

- lib/servers.json
I've got a new server up and tested it to be functional.
> Add new ElectrumX server to servers.json

- contrib/build-osx/osx.spec
Hopefully this is elegant/sane enough.
Not a huge PyInstaller expert here but this was the most reasonable thing I could come up with that is least hackish.  Hopefully. :)
> Added workaround for PyInstaller with PyQt5 5.10 for mac to get the right Qt Style

- electron-cash
- lib/util.py
These are just a few small changes to get the future [android app](https://github.com/marceloneil/electron-android-wip) to work, they shouldn't affect anything at all.
> New android environment variables

- gui/qt/paytoedit.py
Fixes #560 
It's a pretty simple fix which allows cashaddr to be matched with regex
> fix regex to support cashaddr

- ios/make_ios_project.sh
I'm sorry.. I had the wrong make_ios_project.sh in my repo.  Sorry.  Promise this is the last PR.. no pr spam!
> oops, version check was wrong on make_ios_project.sh

- lib/servers_testnet.json
Only just managed to get around to this, server has actually been up a few months.
> Add arihanc.com testnet server

- electron-cash.desktop
Easy way to start testnet version from linux DE
> Add testnet mode to .desktop file

- contrib/make_apk
> ELECTRUM_VERSION -> PACKAGE_VERSION

- contrib/package_plugin.py
- gui/kivy/uix/dialogs/settings.py
- gui/qt/external_plugins_window.py
- gui/qt/main_window.py
- lib/base_wizard.py
- lib/plugins.py
- lib/simple_config.py
- lib/util.py
See the PDF posted in the slack for an overview of these changes.
> External plugins, UI.

- gui/qt/seed_dialog.py
> fix the title of the seed dialog

- setup.py
Improved version of the reverted commit from #625.
> Fix `setup.py` argument parsing for real

- gui/qt/main_window.py
After the “tremendos response” to #665, I'm just gonna propose the change mentioned in that issue for merging. If you have any objections please say so, otherwise I think it really won't hurt to have this in *Electron-Cash*.
> Change the wallet copy function from `shutil.copy2` to `shutil.copyfile`

- lib/commands.py
- lib/exchange_rate.py
- lib/interface.py
- lib/mnemonic.py
- lib/network.py
- lib/paymentrequest.py
- lib/pem.py
- lib/simple_config.py
- lib/storage.py
- lib/tests/test_commands.py
- lib/wallet.py
- lib/websockets.py
- lib/x509.py
Fixes #766 
A few commits here:
* Read files as utf-8. Not directly related but I merged the cherry-pick so may as well
* Fix `lib/pem.py`
* Change setconfig to correctly write url_rewrite to config
* Store address as a string when writing payment request files
> Fix payment requests

- lib/address.py
Fixes unicode decode errors for ScriptOutputs in OP_RETURN txs.
> Fixes #800

- gui/qt/main_window.py
- lib/address.py
> add <push> and <hex> tag support for op_return tool

- lib/servers.json
Not sure why the ports for my server were changed; In any case, it's only listening on `50001` and `50002`
> Fix dragon.zone server ports

- gui/qt/address_dialog.py
> fixes issue #836

- ios/ElectronCash/electroncash_gui/ios_native/addresses.py
- ios/ElectronCash/electroncash_gui/ios_native/gui.py
- ios/ElectronCash/electroncash_gui/ios_native/newwallet.py
- ios/ElectronCash/electroncash_gui/ios_native/receive.py
- ios/ElectronCash/electroncash_gui/ios_native/utils.py
- ios/ElectronCash/electroncash_gui/ios_native/wallets.py
- ios/copy_back_changes.sh
- ios/make_ios_project.sh
- Electron Cash LLC transfer makes it possible for Secure Enclave to ask user to re-encrypt their wallet passwords.  This handles this.
- Fixes various iOS crash issues (CrashReporter reports): #818, #821, #822, #823, #838
> Misc iOS fixups for a bunch of issues

- ios/ElectronCash/electroncash_gui/ios_native/gui.py
- lib/i18n.py
It's the most complete translation we have, actually.
> Added South American Spanish as a supported language. 

- ios/CustomCode/CWStatusBarNotification/CWStatusBarNotification.m
- ios/CustomCode/HelpfulGlue.m
- ios/ElectronCash/app.py
- ios/ElectronCash/electroncash_gui/ios_native/appdelegate.py
- ios/ElectronCash/electroncash_gui/ios_native/coins.py
- ios/ElectronCash/electroncash_gui/ios_native/contacts.py
- ios/ElectronCash/electroncash_gui/ios_native/gui.py
- ios/ElectronCash/electroncash_gui/ios_native/history.py
- ios/ElectronCash/electroncash_gui/ios_native/utils.py
- ios/Resources/AddressConverter.xib
- ios/Resources/AddressDetail.xib
- ios/Resources/CoinsDetail.xib
- ios/Resources/ContactDetail.xib
- ios/Resources/PrivateKeyDialog.xib
- ios/Resources/SignVerify.xib
- ios/make_ios_project.sh
- lib/wallet.py
- This fixes layout issues and other UI issues introduced with the new iOS 12.
- Adds "blurring" of wallet screen when resuming app and unauthenticated. No ore sensitive info exposed to the user!
- Fixed a few esoteric bugs/exceptions
- MASSIVE performance boost for large wallets. Removed a huge bottleneck in updating the history and the contact-specific history. App is more responsive when synching huge wallets with huge histories now.
- Various other tweaks and tuneups
> [iOS] Bugfixes for iOS 12, feature additions, and massive performance boost for large wallets

- lib/paymentrequest.py
Noticed it's still sending the old user agent
> Fix user agent incorrectly reporting old electrum agent string

- ios/CustomCode/UIKitExtras.h
- ios/CustomCode/UIKitExtras.m
- ios/ElectronCash/electroncash_gui/ios_native/amountedit.py
- ios/ElectronCash/electroncash_gui/ios_native/gui.py
- ios/ElectronCash/electroncash_gui/ios_native/send.py
> [iOS] Got BIP70 (bitpay) working

- .gitignore
- contrib/build-wine/README.md
- contrib/build-wine/build-electrum-git.sh
note -- restores previous function of having hardcoded release tag
> Further improvements on windows building

- contrib/build-wine/deterministic.spec
- contrib/build-wine/prepare-wine.sh
- lib/qrscanner.py
Based on https://github.com/spesmilo/electrum/pull/3874
Confirmed to work on Windows 10, at least.
> zbar for windows

- contrib/osx/osx.spec
This was inspired by Electrum's latest commit which in turn was inspired by one of our commits.  Oh the wheel of life! Shiva! Creation and destruction!
> [macOS] Fixup to OSX spec file to be more case insensitive

- android/app/src/main/java/org/electroncash/electroncash3/Wallets.kt
Probably fixes #1046, though I can't reproduce it.
> Use application context in onShowDialog (fixes #1046)

- android/app/src/main/java/org/electroncash/electroncash3/Util.kt
- android/app/src/main/java/org/electroncash/electroncash3/Wallets.kt
#1050 and #1052 are continuing to affect a lot of people, so after this is merged I think we should make a new release to Google Play. (There are a few other less common Android crash reports outstanding, but I won't have time to deal with them until next week.)
> Android fixes

- gui/qt/main_window.py
see title
new installs currently default to Legacy.
> default to CashAddr instead of Legacy addresses

- lib/storage.py
fixes #1104
Shows this error instead on bogus json
> Sanity check on loaded wallet

- plugins/digitalbitbox/digitalbitbox.py
As implemented in upstream electrum https://github.com/spesmilo/electrum/pull/4895 messsages to the BitBox are now authenticated by appending an HMAC. Since this uses some encoding functions from upstream electrum, these have now been defined in the digitalbitbox plugin file. They can be moved to their appropriate place in bitcoin.py once upstream changes are ported.
Also includes a small fix to the seed command from upstream https://github.com/spesmilo/electrum/pull/4906 .
> Append HMAC to BitBox messages

- lib/servers.json
Will also highly recommend new non-onion servers to gradually remove TCP port option (and block with firewall on their server) on the clearnet side.
> Add an onion server

- lib/exchange_rate.py
Coinbase seems to have changed their api endpoint, adapting.
> Fix Coinbase exchange rate api

- electron-env
fix ubuntu installation into virtual env
> fix ubuntu installation into virtual env

- plugins/ledger/ledger.py
> Ledger: Improve handling of locked Ledger devices

- contrib/requirements/requirements-hw.txt
- gui/qt/installwizard.py
- lib/base_wizard.py
> Hw Wallets: Improve how missing libraries are handled

- lib/transaction.py
> fix barfing on certain weird scriptsigs

- README.rst
Adds short section on manually installing the packages often missing from Debian based systems
> [Docs] Debian packages

- plugins/hw_wallet/plugin.py
- plugins/ledger/ledger.py
The multiple transaction output code is taken from Electrum with a few minor modifications.
> Ledger: Support OP_RETURN and multiple transaction outputs

- lib/servers.json
> Add Johoe's onion server

- gui/qt/console.py
Without this you can exit the keyboard focus from the console as the Tab key is used for completion.
> Console: Escape key exits keyboard focus

- gui/qt/__init__.py
- gui/qt/style_patcher.py
> Dark Theme: Fix some disabled items being too dark

- gui/qt/address_dialog.py
- gui/qt/main_window.py
- gui/qt/util.py
This PR adds copy buttons to the Address Converter and fixes the alignment and hover effect of the buttons.
> Qt: Input widgets update

- lib/servers.json
- lib/servers_testnet.json
Hi, please see the below request to add the blains.org main and testnet servers + onion.
> Add theblains.org servers

- gui/qt/main_window.py
> OP_RETURN: Fix off-by-one in error "message too large"

- gui/qt/udev_installer.py
Turns out not all distros support uaccess so we check for plugdev group and add it if it exists.
> Linux: Check for plugdev group in udev installer

- .gitmodules
- contrib/build-wine/_build.sh
- contrib/build-wine/deterministic.spec
- contrib/build-wine/docker/Dockerfile
This patch also addresses some obscure build differences between Linux and macOS docker hosts.
> Windows: Add zbar binary built from mchehab/zbar repo

- plugins/ledger/ledger.py
From Telegram:
> Any idea what error “dongle is temporarily locked - please unplug it and replug it again” means?
Users can be easily confused by just saying dongle or device so we should refer to devices by their names. This also makes more messages available for localization.
> Ledger: Make messages refer to the device by name and enable localization

- gui/qt/main_window.py
> Main window: Add keyboard accelerators to the Send and Converter tab

- gui/qt/qrtextedit.py
Uses the existing button for reading text files and adds the ability to load an image file which will be scanned by the QR scanner. It rejects multiple QR codes at the moment.
> QR text editor: Allow scanning image files using the QR reader

- gui/qt/qrreader/camera_dialog.py
The video frames we get can be in a different resolution than we requested. We can either scale the frames to the desired resolution, which has a performance impact, or we can switch to that resolution.
This patch switches to the resolution of the incoming video stream.
> QR Camera: Switch resolution if frames don't match

- gui/qt/main_window.py
- gui/qt/transaction_dialog.py
- gui/qt/util.py
- lib/network.py
- lib/transaction.py
Note this works pretty well. I am even caching the results and looking in wallet first.
~~TODO: Perhaps load balance this across connected servers.  For now it really works rather well.~~
Edit: It now hits all servers if enabled.
It's default OFF.
> Fetch Input data for TX's (Amount, Address, etc) -- for the Transaction Dialog, asynchronously

- contrib/build-linux/appimage/_build.sh
We build our own mksquashfs from squashfskit which supports generating reproducible squashfs images. We use a small wrapper script to remove the -mkfs-fixed-time which appimagekit passes but squashfskits mksquashfs does not support.
> AppImage: Make build reproducible

- contrib/build-wine/_build.sh
- contrib/make_zbar
commit 1d51925e6cc9151f4a73781989f21fcd7b57ef32
7235b1facf889d94ab9d37c5d8250c1ee3cd4df3e243fdf88305231d0c93f318 libzbar-0.dll
e9a25789cc10727ba03ae53aa5ec88b0ad1db4d5bc0e3dd0cc834d072eb42056 libzbar.so.0
> Zbar: Switch to tagged version 0.23

- plugins/shuffle/qt.py
It was due to signals/slots for objects living in different threads being connected to lambdas... and PyQt not being able to send the slot callback to the correct receiver (wrong thread)... I think. 
What's more I think the disconnect() calls, combined with being in the wrong thread -- led to some sort of chaos inside PyQt and ended up disconnecting the wrong connections..I think.
Anyway I rewrote this code to not be so byzantine and to be more straightforward and it actually no longer reproduces the "disappearing menu actions" bug.
> Fix #1223 "Disappearing Menu Actions" bug

- plugins/keepkey/keepkey.py
Starting with Windows 10 build 1903 HID enumeration using cython-hidapi is broken for KeepKey.
To work around this we register an enumerate function with the device manager that uses keepkeylib's WebUsbTransport.enumerate to get the connected devices. This uses libusb to do the enumeration is not affected.
https://github.com/spesmilo/electrum/issues/5437
If there is an issue with the driver not getting installed (Code 29), use Zadig to install the driver:
https://zadig.akeo.ie/
> KeepKey: Fix device enumeration on Windows 10 build 1903

- gui/qt/address_list.py
- gui/qt/external_plugins_window.py
- gui/qt/main_window.py
- gui/qt/update_checker.py
- gui/qt/util.py
- ios/ElectronCash/electroncash_gui/ios_native/addrconv.py
- ios/ElectronCash/electroncash_gui/ios_native/contacts.py
- ios/ElectronCash/electroncash_gui/ios_native/newwallet.py
- ios/ElectronCash/electroncash_gui/ios_native/send.py
- plugins/email_requests/qt.py
- plugins/labels/qt.py
- plugins/shuffle/qt.py
- plugins/trezor/qt.py
Update some strings, see commits.
> Localization updates

- lib/web.py
* Missing 2 imports
* typo in urllib
> Fix for missing libs and typo

- contrib/build-linux/appimage/_build.sh
> AppImage: Fix some warnings and speed up build

- gui/qt/history_list.py
- gui/qt/qrcodewidget.py
- gui/qt/transaction_dialog.py
- gui/qt/util.py
The transaction dialog is now completely keyboard friendly.
> Improve keyboard navigation in TxDialog and HistoryList

- lib/util.py
This also adjust the cutoff for the "about 1 day / month / year" text to 1.5 days / months / years, just like with hours.
It also fixes the since_date parameter to be converted from timestamp just like from_date. This will happen only when since_date is an integer or float to not break any code.
> Localization: Make age and time_difference function translatable

- lib/util.py
`android_data_dir` is relatively slow because it involves several Java method calls. Caching its return value solves the performance problem, and makes Android sync speed similar to other platforms.
Why the blockchain file is opened and closed thousands of times per chunk is a question for another day...
> Fix Android sync performance

- gui/qt/util.py
- lib/keystore.py
- plugins/hw_wallet/plugin.py
- plugins/hw_wallet/qt.py
- plugins/ledger/ledger.py
Hopefully closes #1598 .
This is a work-in-progress for now -- I need to make sure the refactor didn't break anything with the other wallets (it shouldn't, as I read the code -- but I will need to test to make sure).
Will write a better description here when done.
> [WIP] Ledger Nano X Fixes

- lib/tests/test_transaction.py
- lib/transaction.py
In the case of nonminimal push forms in the scriptSig, we were parsing
those inputs then reconstructing them with the minimal push opcode, which
would result in weird things like the wrong TXID being shown in the
tx details dialog.
> prefer verbatim scriptSig for (re)serializing complete transaction inputs

- lib/i18n.py
The translation is at 46% now and looks already usable.
> Add Swahili to the language list

- android/app/src/main/java/org/electroncash/electroncash3/Network.kt
> Android: allow specifying a server which isn't in servers.json

- .gitignore
- lib/commands.py
- lib/mnemonic.py
- lib/simple_config.py
- lib/tests/test_wallet.py
- lib/wallet.py
Reverts Electron-Cash/Electron-Cash#1633
> Revert "Added create/restore functionality in RPC, fixes"

- lib/servers.json
Greetings,
I started a server and I plan to maintain it. I would like to offer it to the world!
> servers.json: add greedyhog.ddns.net

- lib/transaction.py
As explained in comment, this means that signing/verifying a many-input transaction goes from O(N^2) to O(N).
I'm using this in Fusion since it involves ~100 input transactions. The default behaviour will remain uncached.
> transaction.py: allow caching hashPrevouts, hashSequence, hashOutputs

- gui/qt/__init__.py
Previously if Ctrl-C were pressed, Qt would shut down hard and not give
a chance for plugins to run their `on_close_window` hook. This modifies
the signal handler to emit a Qt signal instead which results in .close
being called on all windows. Note, a direct call to .close is not
appropriate -- even though it is called in main thread, the SIGINT handler
may interrupt execution at any point such as while a critical lock is
held, thus causing a freeze if the window-close hook tries to take same
lock. Hence also the importance of using a QueuedConnection.
Also I had to fix the `close` function here to make a copy, as windows
remove themselves from `.windows` on closing! For some reason it was not
making a 'list modified during iteration' exception, rather it was just
failing to close some …
> softer shutdown on Ctrl-C / SIGINT

- gui/qt/address_list.py
- lib/schnorr.py
- lib/tests/test_schnorr.py
- tox.ini
Aside from #1647, these are the remaining changes I needed to make to main code for fusion to work.
Lazy of me to put them all in one PR but they are minor.
(see commit messages for some additional detail / justification on each change)
> Misc mainline changes from fusion

- plugins/satochip/qt.py
- plugins/satochip/satochip.py
see the following issues:
https://github.com/Electron-Cash/Electron-Cash/issues/1712
https://github.com/Electron-Cash/Electron-Cash/issues/1713
> Patch: [satochip] Electron crashes when cancelling a PIN change or seed reset

- contrib/build-linux/appimage/Dockerfile_ub1604
- contrib/build-linux/appimage/Dockerfile_ub1804
- contrib/build-wine/docker/Dockerfile
Not sure if you want to merge these now or wait for next release, but here they are.
> Dockerfiles update for git version

- gui/qt/network_dialog.py
New .onion URLs are quite long and it is hard to remember which server is which. This patch adds a `display` key that can be added to Tor servers in `servers.json` to give them a short name. Such a server is then listed as "\<display\> (.onion)" and gets a Tor icon in the server list.
> Server list: Add 'display' key to give Tor servers a short name

- gui/qt/network_dialog.py
- lib/servers.json
- lib/servers_testnet.json
> Servers: Add loping.net .onion servers

- gui/qt/network_dialog.py
> Network dialog: Add tor icon to node list as well

- gui/qt/network_dialog.py
The state of the "Use tor" checkbox is used to determine whether to show .onion servers in the server list. This used to not be saved and only initialized when switching to the proxy tab, causing .onion server to not be shown.
This patch changes it so that the state of the checkbox is saved. It also removes the proxy_settings_changed code that resets the box to unchecked when the dialog opens. When the user chose to use tor, we disable the ability to change the settings instead.
> Network dialog: Fix not showing .onions before switching to the Proxy tab

- lib/network.py
based on ABC validation.cpp and consensus/tx_verify.cpp and policy/policy.cpp
> Tweak / add more broadcast error messages

- lib/web.py
> Update ViaBTC explorer address

- gui/qt/invoice_list.py
- gui/qt/request_list.py
- gui/qt/util.py
- lib/commands.py
- lib/network.py
- lib/paymentrequest.py
- lib/util.py
- lib/wallet.py
This pull request backports `payment_received` for better cross-electrum compatibility, also fixing `get_request_status` and making it independent of sync state.
Backport from exact commit: spesmilo/electrum@70cd29f9e1d442863492aef69faf191e6ba40a30
All tests pass.
> Added payment_received event

- lib/servers.json
> servers.json: update greedyhog's server

- gui/qt/main_window.py
The amount of unconfirmed and unmatured coins was not a localizable string, this has been fixed. The code has also slightly improved by using a string join to build the final string instead of adding spaces in the parts of the string.
> Status bar: Add missing localization strings and improve code

- plugins/shuffle/qt.py
- setup.py
(borrowed from cashfusion dev branch)
> Small shuffle fixes

- lib/interface.py
- lib/network.py
- lib/util.py
I've been noticing very slow startups with my CashFusion wallet (>6000 subscription requests), which are triggering unreliability due to a timeout.
This is a set of patches to reduce the slowness (which was caused by round trip latency), and also remove the seemingly unnecessary timeout which was causing the unreliability problem. There is also a general cleanup of the code involved.
> Faster Network connections

- lib/servers.json
domain and port change observed
> Update criptolayer server

- lib/tor/controller.py
This first instructs the Tor process to shut down via the control port, then waits for the process to exit. This will handle almost all cases.
If the process does not shut down within 1 second we send it a shutdown signal via the OS and wait indefinitely for the process to exit.
This also correctly handles `ProcessLookupError`, which can occur when killing a process.
closes #1892
> Tor: Make process shutdown more robust

- lib/interface.py
- We redid the TcpConnection.match_hostname function to call into the
`ssl.match_hostname()` function which implements the full RFCs for SSL
cert hostname matching.  Likely the original implementation targeted
Python 2 which lacked this function.  There is no need to implement
hostname matching ourselves, when Python went to the trouble to fully
implement the RFC's.  This fix adds wildcard certificate support to
Electron Cash.
- We now always accept CA-signed certs, even if a previous conflicting
self-signed pinned cert existed in `~/.electron-cash/certs`.  This closes
issue #1327.
> SSL Certs: Accept wildcard certs, accept CA-signed replacing pinned

- plugins/fusion/qt.py
Just not showing the CashFusion icon on non-fusable wallets is bad UX because the user will never know why the button is missing. Instead we show the icon as disabled with a message indicating why it is disabled.
> CashFusion: Show disabled icon and add message on non-fusable wallets

- plugins/fusion/conf.py
> Fusion: Remove example server

- plugins/fusion/fusion.py
We want to make the 'fee fuzzing' get larger for the higher tiers, so it (and the 'excess fee') needs to be tier-dependent instead of fixed.
At the same time, add more funds/fees sanity checks.
(Have tested this change with dozens of fusions, it is working smoothly.)
> CashFusion: more flexible fee fuzzing logic; more funds safety checks

- plugins/fusion/fusion.py
- plugins/fusion/plugin.py
Auto fusion will happily send up to 3 coins from same addr into
a fusion, basically doing a 'free consolidation'. But they shouldn't
count as distinct entities towards our privacy-minimum of 11
inputs+outputs contributed to a fusion.
> [fusion] include 'distinct coins' concept when enforcing privacy threshold

- gui/qt/network_dialog.py
This is needed for the dutch translation, see:
https://crowdin.com/translate/electron-cash/532/en-nl#29384:drl:340:BigBlockIfTrue
> Network dialog: Add capitalized Tor binary name

- setup.py
Changed icon install directory to the proper one reflecting icon dimensions (256x256) and added install for the scalable icon.
> Fix icon install directory and add install of svg icon

- electroncash_gui/qt/qrtextedit.py
Add an option in the 'Pay to' context menu to scan the current screen
for a QR code.
If someone knows how to easily convey that action as a 16x16
black-and-white icon that someone should probably do an icon for it.
> Scan the current screen for QR code

- electroncash_gui/qt/qrtextedit.py
Look at all screens when scanning for a QR code.
Also add a context menu to the QR icon.
> QR scan from multiple screen and add context menu

- electroncash/exchange_rate.py
See discussion in #878. @cculianu and @imaginaryusername were in favour, and now also me. @rt121212121 was apparently neutral.
I'll merge this if nobody objects within the next few days.
> Enable fiat by default

- electron-cash
pylint was indicating that `main()` had [too many execution branches, too
many local variables, and too many statements](https://pylint.pycqa.org/en/latest/technical_reference/features.html#design-checker-messages).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/electron-cash/electron-cash/2095)
> Refactor main() into functions

- electroncash/tor/controller.py
Tor 0.4.5.x switched to a new format for the port announcements. This changes it so it can understand both the new and the old message format.
> Tor: Update message parser to support version 0.4.5.x

- setup.py
See https://github.com/Electron-Cash/Electron-Cash/commit/15968daf7613eaea7ce7ee0668582cc2d835efb8#r47889408
> setup.py: Fix typo

- MANIFEST.in
> Add requirements-binaries.txt to manifest

- electroncash/base_wizard.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/electron-cash/electron-cash/2209)
> Shorten boolean expression, use double quotes

- contrib/sign_packages
- electroncash/coinchooser.py
- electroncash/mnemonic.py
- electroncash/old_mnemonic.py
- electroncash/plot.py
- electroncash/tests/test_bitcoin.py
- electroncash_gui/qt/main_window.py
- electroncash_gui/qt/network_dialog.py
- electroncash_gui/qt/password_dialog.py
- electroncash_gui/qt/qrcodewidget.py
- electroncash_gui/qt/util.py
- electroncash_gui/stdio.py
- electroncash_gui/text.py
- electroncash_plugins/hw_wallet/cmdline.py
- electroncash_plugins/keepkey/keepkey.py
- electroncash_plugins/ledger/auth2fa.py
- electroncash_plugins/ledger/ledger.py
[Backport from Electrum](https://github.com/spesmilo/electrum/pull/7125) for small style changes.  Also refactored two long lines and changed two lists to sets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/electron-cash/electron-cash/2211)
> Style changes (from backport), small refactorings

- electroncash/wallet.py
Related issue: https://github.com/Electron-Cash/Electron-Cash/issues/2213
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/electron-cash/electron-cash/2234)
> Remove unreachable line of code

- electroncash/currencies.json
- electroncash/exchange_rate.py
Fixes #2283 
Adding custom "exchange" using bitstamp and yadio to get ARS rate
> Add exchange ratio for ARS

- electroncash/servers.json
- electroncash/servers_testnet.json
update kisternet onion to v3 on mainnet
add kisternet v3 onion to testnet
> kisternet servers

- electroncash/address.py
- electroncash/networks.py
BitPay deprecated it 4 years ago in favor of CashAddr
> Remove ADDRTYPE_*_BITPAY

- electroncash_plugins/fusion/server.py
Adds 10BCH (1,000,000,000 SAT) Tier
> Add 10BCH fusion tier

- electroncash_plugins/ledger/ledger.py
I tested a little, and it works for me.
relates to #2417
> Ledger: Add Nano-S-Plus USB device ids

- electroncash/tor/controller.py
Due to the `close_output` argument in stem's `launch_tor_with_config` not being passed to `launch_tor` the Tor process' `stdout` is closed which makes the Tor logging not work.
We monkey patch `launch_tor` to always set `close_output` to `False`.
This will not be needed anymore when a new stem version that includes this commit is released:
https://github.com/torproject/stem/commit/7a4357b2c21d0af5088c1cafce0800fc63cebbb4
> Tor: Fix closing of stdout on Windows

- electroncash/exchange_rate.py
This PR fixes internal exchange rate representation
Most fx rates providers return floats in their APIs, but without loss of precision (basically like a string but not a string)
But when storing that rate, Decimal(float) gets into a fairy long string, i.e. `100.6200000000000045474735088646411895751953125`
But if to do a small hack, this is, convert float to str and then to Decimal, we get a nicely formatted string: `100.64`
This PR uses a new function to convert all rates this way.
Note: this should probably be done for history rates too, but I didn't want to touch it yet as it requires more refactors, that is, to use Decimals everywhere (i.e. `Decimal('Nan')` instead of `None`)
Mostly backports the work done by electrum devs (we discussed it with them): …
> Normalise exchange rate

- electroncash/commands.py
This adds the `freeze_utxo` and `unfreeze_utxo` RPCs.
Roughly ported from https://github.com/spesmilo/electrum/commit/bc6f2926f4b11c7d4293c7c286f7aec1a9889e03.
> commands: add freeze_utxo and unfreeze_utxo RPCs

- .github/workflows/run-tox.yml
- .gitignore
- electroncash/tests/regtest/test_daemon.py
- tox.ini
Run test suite on python 3.7..3.10 on win, macos and linux. Executed on each pull request.
> Run tox in github action

- electroncash/wallet.py
By small modifications, now if amount is None or 0, instead of returning PR_UNKNOWN get_request returns PR_UNPAID. And because of how the detection code works, it will be unpaid if address is empty, and once any payment arrives it will get paid
To get partial payments to work, I needed to just return tx hashes we were able to detect (even if they don't fulfill the full amount yet)
> Allow zero-amount and partial payments in invoices

- .github/workflows/build.yml
Perform builds of AppImage, macOS, win and sourcedist on the master branch each Monday 00:00:00 UTC.
> Add builds to GitHub Actions

- README.rst
Remove Travis and Coveralls badges.
Add GitHub Actions build badge.
Remove references to Python 3.6.
> Cleanup of top README

- electroncash/tests/regtest/test_rpc_misc.py
- electroncash/tests/regtest/test_rpc_payment_request.py
- electroncash/tests/regtest/util.py
Add basic payment request test
> Split regtest in separate files

- electroncash/web.py
* https://twitter.com/3xplcom/status/1617614747339489281
* https://3xpl.com/bitcoin-cash
> Explorer: Add 3XPL explorer

- contrib/build-wine/docker/Dockerfile
> Bump winbind

- contrib/build-linux/appimage/Dockerfile_ub1804
Fixes a build error with broken dependencies
> Bump libssl-dev for AppImage build

- .github/workflows/run-tox.yml
This allows a manual trigger of test jobs
> Add workflow_dispatch to GH Test workflow

- electroncash/servers.json
quite juicy machine, hope it can help. tg: @moleccc
> add fulcrum.criptolayer.net to servers.json

- electroncash/servers.json
Looking to add my server to the list!
> Additional Fulcrum Server

- electroncash_plugins/satochip/satochip.py
see:
https://github.com/bitjson/cashtokens#token-encoding
For cash token tx preimage signature, we use the pysatochip 'sign_transaction_hash' method since the tx preimage format is not backward compatible with legacy Bitcoin Cash preimage tx serialization.
Note that if the 2FA (2-Factor-Authentication) option is enabled in the Satochip, cash-token tx is not fully supported yet by the 2FA android app. The app will not be able to parse the new tx format (show an error instead) but will allow blind signing (signing the request without displaying it on the android app screen). This will be corrected in a future release.
For maximum backward compatibility with 2FA, we only use 'sign_transaction_hash' for preimage tx with cash token. For non-cash-token preimage, we still use the (well …
> Add support for Cash Token in Satochip

- contrib/build-wine/docker/Dockerfile
- electroncash/tests/regtest/docker-compose.yml
> Build: Update winbind package version for Wine build

- contrib/build-linux/appimage/_build.sh
- contrib/requirements/build-constraint.txt
- contrib/requirements/requirements-hw.txt
- electroncash/tests/regtest/docker-compose.yml
See https://github.com/trezor/cython-hidapi/issues/155
Depends on #2664
> Build: Fix hidapi installation and require Cython<3

- contrib/build-wine/docker/Dockerfile
- electroncash/tests/regtest/docker-compose.yml
> Build: Update vs_installer.ops checksum

- electroncash/servers.json
Server was accused of spam, highly suspect the long-running tor instance was causing the problem, so I need to remove this. Maybe one day I'll be able to run an onion instance separately...
> remove my onion server

- electroncash_gui/qt/console.py
This is a backport of https://github.com/spesmilo/electrum/commit/441da52b513cb3f2470ac35978b16eefdf1d07de
Fixes #2674
> [backport] fix more DeprecationWarnings

- electroncash/tests/test_interface.py
This is a backport of https://reviews.bitcoinabc.org/D14440
> [tests] Skip test_interface if offline

- electroncash/plugins.py
The CashShuffle icon isn't working anymore and when investigating I found that relative imports in plugin GUIs and external plugins broke when we merged #2662.
```
|  3.762| |00| Plugin error
Traceback (most recent call last):
File "H:\dev\Electron-Cash\electroncash\plugins.py", line 610, in run_hook
r = f(*args)
File "H:\dev\Electron-Cash\electroncash_plugins\shuffle_deprecated\qt.py", line 711, in on_new_window
self.add_button_to_window(window)  # unconditionally add the button if compatible -- they may want to enable it later
File "H:\dev\Electron-Cash\electroncash_plugins\shuffle_deprecated\qt.py", line 694, in add_button_to_window
window.__shuffle__status__button__ = ShuffleStatusBarButtonMgr(self, window)
File "H:\dev\Electron-Cash\electroncash_plugins\shuffle_deprecated\qt_status_ba …
```
> plugins: Fix relative imports in plugin GUIs and external plugins

- electroncash/servers_chipnet.json
- electroncash/servers_scalenet.json
> Update for electroncash.de servers: remove scalenet node, chipnet

- .github/workflows/run-tox.yml
From "build" to "test" to avoid confusion
> Change name of GHA step

- contrib/make_openssl
Thanks to Jonas & Calin for helping with this in Telegram...
> Use native architecture when building on macos

- electroncash/wallet.py
> Correct variable in token_data error of add_transaction().

- electroncash_gui/qt/request_list.py
- electroncash_plugins/email_requests/__init__.py
- electroncash_plugins/email_requests/qt.py
- Updated the email plugin settings to allow adding an alias
- Added a new email dialog 
- Added a nice looking html email with a QR code and payment info attached
Settings
Email Dialog
Email size: 11.5Kb
> Update email requests

- contrib/requirements/requirements-binaries.txt
> Restrict PyQt5-sip<=12.12.2

- .github/workflows/audit.yml
> audit: Ignore requests vulnerability

- contrib/build-linux/appimage/Dockerfile_ub2004
- contrib/build-wine/docker/Dockerfile
This will make the AppImage and win builds green
> build: Bump git versions

- contrib/build-linux/appimage/Dockerfile_ub2004
```
git=1:2.25.1-1ubuntu3.13
wget=1.20.3-1ubuntu2.1
```
> build: bump AppImage package versions

- contrib/build-linux/appimage/Dockerfile_ub2004
Fixes issue in deterministic build
> Bump libudev

- electroncash/servers.json
- electroncash/servers_testnet.json
> Replace electrs.electroncash.de with fulcrum2.electroncash.de

- .github/workflows/build.yml
- contrib/build-wine/docker/Dockerfile
Also fix artifact setting for GHA
> Bump git package in win build

- electroncash/servers.json
- electroncash/servers_chipnet.json
- electroncash/servers_testnet.json
- electroncash/servers_testnet4.json
> servers: remove electroncash.de

- .github/workflows/audit.yml
Looked thru the issues reported by the audit tool and added ignores for the ones not affecting our builds, which was all of them.
> Whitelist issues with pip-audit
