Electron-Cash/Electron-Cash

- gui/kivy/main_window.py
- gui/qt/main_window.py
Was going to implement at the parse_input method in transaction.py... but there are many cases where there might not be a wallet, and loading the wallet into transaction.py seemed silly.
> Fix transaction loading to include value if your own transaction.

- lib/simple_config.py
https://stackoverflow.com/questions/2034517/pythons-interpretation-of-tabs-and-spaces-to-indent
My previous merge request I apologize, I replaced tabs with 4 spaces because I misunderstood the way Python2 interprets mixed tabs and spaces.
Currently, Python will replace every tab with 1-8 spaces so that the total number of spaces totals to a multiple of 8.
These two tabs being here randomly could cause problems down the road, so getting them out of the way now would be beneficial.
> Replace tab with 8 spaces not 4 spaces

- plugins/trezor/plugin.py
TREZOR firmware expects signatures not to contain the trailing sighash
byte.  This fixes issue fyookball/electrum#47.
> TREZOR: Remove sighash from input signatures

- gui/qt/main_window.py
Still getting my local environment going so this should get tested by someone else, but the references to using utf-8 in the file were mixed between 'utf-8' and 'utf8'. One was right, the other was wrong. This is a simple switch to make them all 'utf-8' as they should be. This likely would be an issue in the parent project as well.
fixes #173
> Fixed 'utf-8' being referenced as 'utf8'

- gui/qt/main_window.py
filename from 'electrum_labels.json' to 'electron-cash_labels.json'
fixes #117
> issue #117 - export labels filename 

- .gitignore
- lib/tests/sample_tx.py
- lib/tests/test_transaction.py
- lib/tests/test_wallet.py
- lib/transaction.py
- lib/wallet.py
This is an alternative fix for #169. It will also fix the case when a transaction is signed from the command line, when the wallet is online (not when the wallet is offline). This is an alternative to #170, one of the PR's should be chosen.
The large changes are in the tests, the transaction tests have been improved and wallet tests for this issue have been added.
An exception is raised when generating the preimage for signing, if the value of the input is not known.
A new method add_input_values() has been added to the Wallet class which checks a tx and adds the values of the inputs where those values are not already present.
> Add input values to tx in wallet before signing

- lib/blockchain.py
I tested on special testnet after the first commit "move ending/starting timestamp...": still validates the chain.
The second commit just cleans up the leftover testing comments and prints and switches the activation time to the mainnet one (special testnet activation time still there as a comment for easier re-testing)
> move if statements out of loop, cleanup testing comments and prints

- lib/network.py
As mentioned on reddit. Updated to ABC 0.16 and want to change hostname to reflect its cash not bitconnect coin.
Just mainly making this to remind you :)
> Switch bcc.arihanc.com to bch.arihanc.com

- lib/network.py
Provisioned electrumx test server on Bitcoin Cash testnet.
> add electrontest.cascharia.com electrumx test server

- gui/qt/paytoedit.py
This was actually reported on reddit by someone [here](https://www.reddit.com/r/btc/comments/7iexxm/electron_cash_version_30_is_here_for_windows_and/dqy9rgu/) 
When the QR input window is closed without scanning any valid QR code, the `qr_input` function returns a NoneType object. This change is a quick and simple fix to just prevent the resulting `AttributeError`, as seen here:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/Electron_Cash-3.0-py3.5.egg/electroncash_gui/qt/paytoedit.py", line 263, in qr_input
if data.startswith("bitcoincash:"):
AttributeError: 'NoneType' object has no attribute 'startswith'
Aborted
```
> Fix to prevent AttributeError on aborted QR input 

- lib/address.py
The original would throw an exception since both address.py and cashaddr.py live in the same directory, namely "lib".
> Fix intrapackage import of cashaddr

- lib/blockchain.py
Handling a verification exception through `VerifyError` was causing another exception
> Fix VerifyError

- lib/blockchain.py
- lib/networks.py
- lib/servers_testnet.json
Fixes #389 
It's worth mentioning that server `180.235.49.196` seems to be down, and server `electrum-testnet-abc.criptolayer.net` is roughly two and a half weeks behind. Since there are no other testnet servers available, I've left them in for now.
Additionally, block [#1199520](http://tbcc.blockdozer.com/insight/block/00000000aa5a221632243483ae93a8828bb4ee735c91f4c8d16703246b10c6fe) seemingly didn't adjust according to the Nov 13 DAA HF, which I really can't explain. I've hardcoded in the bit verification for now (otherwise it doesn't continue). If anyone has any explanations for this that would be splendid.
> Fix testnet

- plugins/ledger/ledger.py
Fixes #153 
This was tested using the Nano S - I can't verify it would work for the Blue or HW1.
I tested both standard and multisig wallets, along with multiple outputs on the Bitcoin Cash testnet and mainnet.
Most of the code needed for ledger wallet BIP143 transactions was sourced directly from the segwit update of [spesmilo/electrum](https://github.com/spesmilo/electrum), so credit is due there.
> Add ledger wallet support

- plugins/ledger/ledger.py
This PR removes the `distutils` dependency which windows doesn't seem to package by default, bringing ledger compatibility to windows
> Fix ledger on Windows

- README.rst
- contrib/fix_libs_osx.sh
- contrib/make_packages
- Added a shell script to automate rewriting the dynamic loader libpaths: contrib/fix_libs_osx.sh
- Fixed contrib/make_packages to use requirements_osx.txt on Darwin
- Updated README.rst to reflect new contrib/fix_libs_osx.sh
> macOS fixups for building 3.1

- electron-env
- setup.py
- pyqt5 is now distributed as a wheel so it doesn't need to be installed by the package manager.
- ```PYTHONPATH="/usr/local/lib/python3.5/site-packages```" doesn't work on Ubuntu 16.04, python3-qt5 installs in ```/usr/lib/python3/dist-packages```.
- The GUI icons need to be generated for electron-cash to launch.
With this pull request ````electron-env```` works directly after a ```git clone``` provided libqt5 (not pyqt5) libraries are installed.
Tested on Ubuntu 16.04 LTS.
> Fixes electron-env so that it can be run from source.

- gui/qt/main_window.py
It looked like a bug to me that the default filename was 'electrum-cash-private-keys' rather than 'electron-cash-private-keys'.  This PR fixes that.
> Changed default private key export filename to electron-cash-private-keys

- lib/currencies.json
- lib/exchange_rate.py
Fixes #208, Fixes #435 
Addds historical price rates, which fixes a case where users are unable to select any fiat price rates on both android and desktop.
> Add historical price rates

- electron-cash
Resolves #420 
Basically a clearer exception for when a user tries to use a version of python lower than 3.5
> Add version warning

- lib/wallet.py
Fixes #454
Issue occured because `pop()` returns the popped value
> Fixes issue where receive request does not save

- gui/kivy/main_window.py
Fixes #471 
Fixes an issue where the "max" button on the send form crashed the android app. This was caused by an inproperly formated address failing an assertion, fixed by properly formating it.
> Fix max payment on android

- lib/contacts.py
Fixes #489 
Tales of contacts being broken may have been exagerated. However, I'm confused by what [`lib/contacts.py:74`](https://github.com/fyookball/electrum/blob/44cd7f2b94e34a693e6d7fe93f687ef4ffeb6423/lib/contacts.py#L74) is meant to do. It seems that it will take an address and return it's contact title (which would never happen, because the previous if-statement catches all addresses). I feel like this should take a contact title and return an address.
> Fix contact address format

- lib/tests/test_bitcoin.py
Fixes #504
Changed the test to expect an `Exception` rather than `False`. This might not be the expected functionality, so `verify_message` might need to be modified.
> Fix message signing test

- lib/commands.py
used to accept `Address`, now uses a string
makes it work from CLI and RPC
> fixed getrequest

- lib/storage.py
Hi guys,
In my work on the iOS version, I noticed a subtle bug/quirk in storage.py when changing wallet password.  If the user goes from enabling wallet encryption to disabling it (or vice-versa) the change isn't reflected in WalletStorage.is_encrypted() until the app is restarted.
This is because WalletStorage.is_encrypted checks the 'raw' data from the wallet file to answer the 'is encrypted' question -- but self.raw isn't updated properly when executing set_password(), write(), etc after the user requests to go from encrypted/decrypted to its opposite.
Is encrypted:
```
def is_encrypted(self):
try:
return base64.b64decode(self.raw)[0:4] == b'BIE1'
except:
return False
```
How to reproduce:
- Using a wallet that was encrypted and pw protected: Open up the password dialog and tell the …
> Fixed esoteric storage bug when changing password

- contrib/build-osx/osx.spec
This is a pet peeve of mine:
On OSX, if you don't have this key in Info.plist, all Qt apps run in "High Performance GPU" mode always -- which is annoying because it eats battery life.
Note that the Electrum team already has this key in their Info.plist.
Nothing special needs to be done for our Qt app to support this key.  By default, with this key present, if the app uses advanced GPU features (OpenGL), it will auto-switch to the high performance mode, and switch back then it's done.  Qt supports this internally.
This key really should only be set to false (default) for apps that maintain very specific OpenGL state and don't want their GPU swapped from under them (such as Mining apps).
It's safe to set to true for our app, and saves tons of battery life on laptops.  
Tested and works.
> Fix GPU mode on OSX by adding a key to Info.plist

- plugins/hw_wallet/qt.py
- plugins/ledger/ledger.py
Adds cashaddr support for the ledger wallet nano s and blue, as well as irritates the user to update their firmware/libraries if they have cashaddr enabled.
requirements:
* ledger firmware:      1.4.2
* bitcoin cash app:     1.2.5
* python-btchip:        0.1.27
https://github.com/LedgerHQ/btchip-python/commit/7c6d107d0ec2e55484c39849ff9291167cf41fd0
https://github.com/LedgerHQ/blue-app-btc/commit/74f61cf1014572a001e0b0ab5ec330cc347f713a
> ledger: cashaddr support

- org.electroncash.ElectronCash.appdata.xml
- setup.py
Hi! I've been using *Electron Cash* (and its predecessor) for a while and am pretty happy with it. Since I'm not terribly happy however with the current Linux distribution and installation procedure of this software, I did an experiment and tried to create a [Flatpak app](https://flatpak.org/) for it ([Downloads](https://storage.ninetailed.ninja/index.php/s/Zd5HxE6myDs386R) / [“Source code”](https://gitlab.com/ntninja/electroncash-flatpak)).
Not sure if you interested at all offering better distribution methods (and I must say I'm not sure I'm totally sold on Flatpak at this point), but if you are we should probably discuss this in an issue or something. :slightly_smiling_face: 
Anyway, this PR just contains some fixes for detecting the system installation path in `./setup.py` and adds …
> AppStream metadata (cf Flatpak)

- gui/qt/__init__.py
Provide some better information to a user importing a 2fa wallet (directly links to @DarkLordGMS's wonderful guide https://github.com/fyookball/electrum/issues/41#issuecomment-357468208). Probably not as useful as it would have been a few months ago, but better than nothing.
Also fixes #616, as it handles upgrading a 2fa wallet as well.
Issues:
- Only for QT, nothing for CLI
- Doesn't terminate the wizard when you get this error while upgrading a wallet (although it didn't before, and it seems ok)
- The `if '2fa' in str(e)` and/or wrapping everything in a try/catch might be too messy, so suggestions are accepted
> Provide better information to users importing a 2fa wallet

- lib/servers.json
I moved to a new server and did not backup the SSL crt file.
Thus I needed to change the address.
> changed subdomain and updated electrumx version

- contrib/package_plugin.py
- gui/qt/external_plugins_window.py
- lib/plugins.py
- lib/util.py
Commit 1 relating to review by Marcel:
* Remove stale comment about external plugin package name.
* Remove versiontuple comparison function, as tuples can be compared directly for the same effect.
* Add kivy ui support to plugin packaging script. 
* Add standard .md5 file writing to accompany zip file writing in plugin packaging script.
* Increase width of plugin preview window, as it is reported the liability checkbox has it's text cut off on some OS.
Commit 2 fixing more identified polish areas:
* Change checksum function from md5 to sha256.
* Change plugin uninstall confirm dialog from a non-cancellable warning dialog to a Yes/No question dialog.
* Add better display of errors when a plugin the user is trying to add is found to be invalid (more error messages, fallback on error code if …
> Fixes and improvements to the new plugin code

- gui/qt/external_plugins_window.py
This works ok on Windows and Linux but breaks on Mac.
On mac it led to the Plugin Preview dialog never appearing and the app being stuck in a local event loop forever.
This is because macs are more restrictive and a modal dialog window really is modal to its parent -- and this class made its parent be "main window" previously, which was modaled-out.
Now it correctly made its parent be the already-modal "plugins" window.
Everything is peachy.
> Fixed incorrect modal dialog usage on ExternalPluginsPreviewDialog (breaks on Mac)

- gui/kivy/uix/ui_screens/status.kv
- gui/qt/network_dialog.py
1.  Correct title name
2.  Make delete button a red one to warn users "this is a dangerous button to tap"
The red color (1, .4, .3412, 1) in (r, g, b, a) is equivalent to the red negative value (#FF6657) in transaction history list.
> Fixes for Android wallet dialog

- contrib/make_locale
This is required when building the translations as part of the Flatpak build process, because the main build process is strictly offline-only for reproducibility.
See https://gitlab.com/ntninja/electroncash-flatpak/commit/d4a3a7c43572a11817f7afb6957a98811ab06c3c for how this used.
> Allow the `make_locale` script to read the translations from a local archive

- lib/wallet.py
This function had potential bugs in it. 
This fix to the function was pulled from upstream which changed this function circa January of this year, I think.
They have lots of other changes related to usage of locks and "saving unverified tx's to wallet" and all sorts of other stuff, so I couldn't cherry-pick their commits.
Instead, I copy-pasted this one fix.
> fix for issue #757

- gui/kivy/uix/dialogs/settings.py
- gui/kivy/uix/ui_screens/network.kv
- gui/kivy/uix/ui_screens/server.kv
- gui/qt/__init__.py
- gui/qt/seed_dialog.py
- ios/ElectronCash/electroncash_gui/ios_native/network_dialog.py
- ios/ElectronCash/electroncash_gui/ios_native/sign_decrypt_dialog.py
- lib/plugins.py
- plugins/labels/__init__.py
"Electron Cash" naming. For upcoming translations (issue #746).
> Modify translatable strings with "Electron Cash"

- lib/keystore.py
- lib/wallet.py
- plugins/keepkey/plugin.py
- plugins/trezor/trezor.py
Since bitcoincash signs the amount, there is no need to download previous transactions, at least for Trezor. This allows real offline signing.
Unfortunately other hardware wallets (I tested keepkey) don't work without previous transactions, so I added a function to `Hardware_Keystore` to indicate whether the hardware needs them.
Also fixed OP_RETURN txs for KeepKey.
> Offline signing for Trezor.

- gui/qt/amountedit.py
- gui/qt/fee_slider.py
- gui/qt/main_window.py
- lib/simple_config.py
The previous confirmation field "Max fee" had not been in use for some time.  It used to be used to calibrate the fee slider by first setting the max fee, which became the maximum value of the fee slider, and lesser values were extrapolated from it.  
That was then removed so that the slider only allowed one set of fees: from 1-10 sats/byte.  
Now with lower fees in the possible future, we want to allow more flexibility.  But rather than re-introduce the max_fee, which is somewhat convoluted, a simpler setup is proposed:  We just have one field which is a fixed satoshis per Kb, called "customfee" (Custom Fee Rate).  
If customfee is None, then the slider retains the 1-10 sats/byte set.  Otherwise, the singular value of customfee is used in Sats/kB.  Here kilobytes not bytes is preferred …
> Remove max_fee config, replace with customfee

- gui/qt/amountedit.py
- gui/qt/fee_slider.py
- gui/qt/main_window.py
- lib/simple_config.py
What's new:
If "Custom Fee Rate" is specified in preferences then:
1. Fee slider disappears
2. It's replaced by a label (well, a HelpLabel actually) that shows the fee rate as calculated from the custom fee rate and/or manual fee override (manual fee override wins, but the custom fee rate is the initial default)
If "Custom Fee Rate" is not specified in preferences (this is the default on new installs), then:
1. Fee slider is visible and works as normal
2. The aforementioned help label is always hidden.
- Note that I also cleaned up Jonald's code from the last commit and refactored it, and also made it play nice with the esoteric "CPFP" dialog which you can get from an unconfirmed tx, if you right-click on it in "history" and do "Child pays for parent"
> Fee slider modifications and messaging as discussed in Slack on 7/4/18

- contrib/build-osx/make_osx
- contrib/deterministic-build/requirements-hw.txt
- contrib/deterministic-build/requirements.txt
- Locales for the contrib/build_osx/make_osx script were still pulling the old electrum locales. Fixed this to use the new crowding mechanism (from make_locales script)
- Apparently we no longer depend on pbkdf2, so I removed this as a dependency from macOS
I just wanted to let you guys know about this change which is why I made a PR.
I may just merge this soon anyway if I don't hear back from you guys.
> Fixed locales for MacOS and also removed pbkdf2 dependency for MacOS

- gui/kivy/main_window.py
- gui/qt/main_window.py
- gui/qt/network_dialog.py
- gui/stdio.py
- gui/text.py
- ios/ElectronCash/electroncash_gui/ios_native/gui.py
- ios/ElectronCash/electroncash_gui/ios_native/network_dialog.py
- lib/blockchain.py
- lib/commands.py
- lib/interface.py
- lib/network.py
- lib/networks.py
- lib/tests/test_blockchain.py
- lib/verifier.py
- lib/version.py
- lib/wallet.py
- scripts/block_headers
This pull request uses electrumx checkpoints to remove need for pre-checkpoint blockchain sync.  It includes various changes from Electrum adapted for the different checkpoint model.
It comes with recent checkpoint heights and merkle roots included for both testnet and mainnet.  If these are removed (edit `networks.py` and replace the height with None) instead of expecting that height/root, it will fetch at least 3 sets of verification data for the same height from different servers, and won't pass verification stage unless all three match.  The root and height will be printed to the console before it proceeds to use the given header data.
> Use electrumx checkpoints to remove need for pre-checkpoint blockchain sync

- lib/transaction.py
This handles the exception at least and leads to nonsensical partially decoded outputs.
Not sure if this is the correct approach though -- but it's the path of least resistance at least to safeguarding against this buggy code blowing up on invalid scripts.
> Proposed fix to issue #829

- lib/commands.py
JSON RPC broke for the 'deserialize' command due to the introduction of the namedtuple-based classes Address, ScriptOutput, etc.
This corrects that oversight.
Fixes issue #638
> Fix for JSON RPC daemon broken 'deserialize' command (issue #638)

- gui/qt/main_window.py
- ios/ElectronCash/electroncash_gui/ios_native/coins.py
- ios/ElectronCash/electroncash_gui/ios_native/gui.py
- ios/ElectronCash/electroncash_gui/ios_native/history.py
- lib/i18n.py
- Implement tx spam filter -- so when you synch up a new wallet with lots of tx's, it collates them in 30-second intervals and says eg "354 new tx's arrived totaling xx.yy mBCH" rather than what we had before which was a very spazzy notifier.
- Added some tuneups to iOS and desktop Qt.
> Tx notify and other tuneups

- gui/qt/address_dialog.py
- gui/qt/main_window.py
- gui/qt/transaction_dialog.py
- lib/wallet.py
It always irked me that if you kept the address detail window open or the transaction detail window open, they would remain stale and not update as new stuff comes in off the network.
For instance the tx dialog would stay at "Unverified" or "0 confirmations" for all eternity.
And the address detail dialog would never receive updates from the network.
This fixes that.
I added this because Mark Lundberg was also asking for it.
> Made AddressDialog and TxDialog update in realtime

- gui/qt/transaction_dialog.py
- lib/address.py
This is an idea ported over from the SLP wallet. Electron cash currently prints OP_RETURN pushed binary data in a really hideous way. This PR changes it to print in a much nicer way.
Before:
After:
> print OP_RETURN pushes in a nicer way

- gui/qt/transaction_dialog.py
- lib/coinchooser.py
- lib/transaction.py
- lib/util.py
- lib/wallet.py
This was an issue previously that went undetected/unaddresses for a while.
See #860.
This fix:
1. Sets internal 'dust_threshold' to network-wide hard-coded value of 546
2. This has the (desired) side effect of dust outputs no longer being appended to a tx (which caused tx to get rejected). Instead they are added to fee (which is just about the only thing that you can do).
3. User is told about this addition to the fee.
In addition, this PR fixes a formatting issue of the 'fee rate' in the transaction dialog screen (fee was rounded to nearest sat/B, rather than displaying fractional eg 1.25 sats/B fees).
Here is a preview:
> Fix for issue #860 - "Bad Tx's with dust outputs spoiling the fun"

- gui/qt/transaction_dialog.py
As per discussions with Mark Lundeberg, and in preparation for more OP_RETURN action on the blockchain, we think it might be worthwhile to make the tx in/out text area expandable in the tx dialog.
This PR Does that.
See below.  Note how now the Input/Output panes expand to take up vertical space as the window grows.  Note that if the window is shrunk, they do give way and do not eat up any space.  The only difference is that the huge dead area between the buttons and the text fields can no longer happen.  See the below screenshots:
**Before:**
**After:**
> Made inputs and outputs text edit more prominent/take up more space

- gui/qt/main_window.py
- lib/paymentrequest.py
A transaction from a BIP70 invoice should not be broadcasted by the
wallet.
If a valid PaymentACK is received it is up to the merchant to broadcast
the transaction.
This also fixes a nasty race condition where a transaction was
broadcasted before the merchant had ACK'd it which would likley cause
the user to loose money.
Also updated the memo field from "Electrum" to "Electron Cash".
Please note that this need quite a bit of testing. I have only done some tests against BitPay testnet on the desktop version of Electron Cash. This should be seen as a proposal more then a final solution since there probably is some fine tuning and error handling to do.
Fixes #812
> Do not broadcast transaction for a payment request

- gui/qt/transaction_dialog.py
In qt transaction_dialog.py, two things are supposed to happen upon closing (via `closeEvent` function):
* Prompt for save
* Remove self from persisted `dialogs` list (prevent memory leak)
Unfortunately [this does not happen if user presses Escape key](http://doc.qt.io/qt-5/qdialog.html#escape-key), which calls reject() which just hides the dialog and does not invoke closeEvent (I have confirmed this in testing).
This fix makes it so that pressing Esc is equivalent to clicking the Close button.
As a bonus I've included [a fix seen on the spesmilo upstream](https://github.com/spesmilo/electrum/blob/master/electrum/gui/qt/transaction_dialog.py#L176-L179) for the situation where someone has created the dialog directly.
> transaction_dialog.py -- normal close if user presses Esc

- gui/qt/address_list.py
- gui/qt/main_window.py
- gui/qt/utxo_list.py
- lib/wallet.py
This adds the Coin-level freezing facility as discussed in #889.
Below are screenshots of how to control it from the UI.  The coins tab now allows you to freeze on address-level and coin-level
The address tab is unchanged and only freezes on address-level.
The various levels of freezing/unfreezing for a particular coin are color-coded.
A coin is defined as spendable if its address is not frozen and it itself is not frozen.
The two address-level/coin-level freeze flags are set independent of each other.. but this Coins tab UI lets you set both en masse for convenience.
> Implementation of coin-level freeze function in Wallet + Qt GUI

- lib/transaction.py
When signing a transaction, don't overwrite the `x_pubkey` with the `pubkey`.
Hardware wallets want to verify that input addresses and change
addresses belong to the same wallet.  For this they need to know the
`x_pubkey`.
> Preserve x_pubkeys

- lib/servers.json
There are various other new servers to be added later, but these ones definitely seem to be gone.
This reduces the default server list from 15 to 10. Of the 10 remaining, one is TCP-only (not really used), one is IPv6, and one is TOR... so for most users it's really just 7 accessible servers.
> remove dead servers from default list

- lib/transaction.py
This modifies one of the internal functions called by `Transaction.sign()`, to allow inputs to have a type of 'unknown' where the scriptCode (used in signing that input) needs to be provided. This allows the `sign()` method to correctly create signatures for OP_CHECKSIG even for unusual smart contracts. It is still up to the developer to correctly set up the input dictionary, and to serialize the proper scriptSig after the signature operation is done. (`sign()` leaves the signature in the input dictionary's `'signatures'` list)
I have found this particular modification to be essential in coding my custom P2SH codes (atomic swaps and now also coin splitter), so I thought it would be nice to have in mainline. All other necessary code to handle these smart contracts can be done without …
> required mod to allow complex P2SH processing

- README.rst
Combines two things:
1. I am a noob and had no idea how to create the tarball. I think the instructions I added for that are correct.
2. The `make_packages` was failing, I think because Ubuntu 18.04 has --user as a default pip option, which was interfering with usage of --prefix? Anyway, having official/upgraded pip solved it.
With these two things, I managed to make a source-with-packages tarball that ran successfully on a clean Ubuntu. Yay.
> update README for making releases

- gui/qt/exception_window.py
I had an assert exception throwing on code containing < character, like `assert len(s) < 100`. Unfortunately this got truncated to `assert len(s) `, since Qt is interpreting the traceback as html. This change escapes the traceback so < characters don't mess it up.
> Exception reporting window: escape HTML special characters in traceback.

- lib/servers.json
This updates `lib/server.json`, the initial seed list. This list includes 9 servers that will fork off onto the new ABC rules (three BU, six ABC), and 2 servers that will fork off onto the new SV rules. Was generated using `scripts/servers` then modified. Note that the 'version' field has been incremented from 1.1 to 1.4 since all these servers support protocol 1.4.
Many servers were omitted:
* Servers running old node versions (XT 0.11, ABC 0.17, BU 1.3/1.4), not ready for Nov 15 fork day.
* Servers running BU 1.5 / ABC 0.18 with unpatched ElectrumX (they will crash on Nov 15).
* Servers with expired certs.
Survey for reference:
https://docs.google.com/spreadsheets/d/1xFthIiIG1lUBczGwUinazBzjRinuRmCi9h_xfUSAjZM/edit
(plz don't merge yet)
> update default server list

- gui/qt/main_window.py
- gui/qt/transaction_dialog.py
@rt121212121  You are the one that introduced the change that triggered this bug.  Are you ok with my fixup?
See #939  and #941.
> Fixes #941 #939 - When reading tx from file -- None values were populating tx._inputs

- lib/interface.py
- lib/util.py
Based on https://github.com/spesmilo/electrum/commit/ad6dd73a032517651d6e029163628d67039a36d2.
This fixes the problem completely on Android: the error is logged and the network recovers to the normal number of servers within seconds.
Interestingly, the logged error is now "ConnectionAbortedError: [Errno 103] Software caused connection abort". I guess the "Broken pipe" and "Bad file descriptor" errors I was seeing before were because it was continuing to use the socket after it had already been told it was dead.
> Fix infinite loop on network error (closes #994)

- contrib/build-wine/README.md
- contrib/build-wine/build-secp256k1.sh
- contrib/build-wine/build.sh
- contrib/build-wine/deterministic.spec
- contrib/build-wine/prepare-wine.sh
- contrib/osx/make_osx
- contrib/osx/osx.spec
- lib/bitcoin.py
- lib/ecc_fast.py
Do not merge this yet.  It works but I have to figure out the packaging issues (building for OSX and for Winows) -- likely I'll merge in what upstream did.
> Use native libsecp256k1 if available, otherwise fall back to the old slow way.

- gui/qt/address_list.py
See #1042 .
- The code that implemented "restoring the state" for the address list was hard to read and a bit wonky. I made it so it works more generically with any hierarchy of trees and subtrees.
- Restoring the "currentItem" would violate the invariant: it would sometimes cause subtrees that we wanted to stay collapsed to expand if the item is in a collapsed subtree. This fix addresses that. I'm hoping this latter "quirk" is the cause of what you guys saw in #1042.
- The previous code had out-of-spec calls to Qt in that it would sometimes call `setExpanded()` on items that don't live in any tree (the used_item sometimes doesn't live in any tree).  Not sure if that would cause a crash or not but it's definitely not a good thing. See: …
> Fix address list quirk 

- AUTHORS
- RELEASE-NOTES
- lib/version.py
Mark & I are in favor of bumping the version to 3.5:
- This makes it clear that 3.3.x is BCH + BSV and 3.5+ is BCH only.
- This avoids the confusing that exists now with users thinking 3.4 is better/newer/stronger than 3.3. 
- It feels good man.  3.5 has a nice ring to it.
I also went ahead and updated the AUTHORS file.  Let me know if I missed anything in the AUTHORS file or if anything needs changing.
Also added what I remembered happening from the commit logs between last release and now to RELEASE NOTES.
> Bumped version to 3.3.3, updated AUTHORS & RELEASE-NOTES

- gui/qt/main_window.py
This adds a checkbox so you can input the raw scriptpubkey to appear after the OP_RETURN, in hexadecimal. This gives you exact control over the OP_RETURN message and lets you do multiple pushes, non-minimal pushes, etc.. Here's an example of me using it to manually make a [CashAccount](https://www.cashaccount.info) registration (I just clicked preview -- after the screenshot was taken, I then signed and broadcasted it).
> allow raw hexadecimal input for op_returns (binary stuff, multi-pushes, etc.)

- lib/commands.py
Command line outputs reference to the wrong program (and folder, in one line) is kinda annoying.
> Replace Electrum with Electron-cash in text

- gui/qt/network_dialog.py
- lib/network.py
- lib/networks.py
This addresses #1065.
The rationale for this new facility is that we want the user to be able to guard against sybil attacks. As such, we now offer a facility to specify "white listed" servers, as well as have the user manually specify the previously internal-only server blacklist.
Highlights:
- White-list is called "**Default server**" in the GUI to make it a very neutral term (suggested by im_uname).
- The "white listing" facility is **ONLY** used If the user has "Connect to default servers only" checked. *This option is off by default.*
- The white list is fully user-editable
- The default white-list are the servers specified in the `servers.json` file
- The user may also elect to manually blacklist servers (previous to this, the blacklist was managed internally for servers that were …
> [Qt] Anti-Phishing: Network Dialog Whitelist and Blacklist (user editable)

- gui/qt/transaction_dialog.py
- gui/qt/util.py
- plugins/cosigner_pool/qt.py
- Plugin was not really compatible with more than 1 multisig wallet open
- Plugin was not resilient to plugin re-starts
- Listener thread was hanging
- Listener thread was not resilient to server being down or timing out
- Made the "do you want to open the cosigned tx" question dialog default to 'Yes'. (Partially-addresses #1113 )
Refactored most stateful data to per-wallet data structures. Each wallet that is multisig also gets its own listener thread and made the listener thread poll once every 10s rather than 30s.
Plus various other nits fixed.
> [Qt] [Cosigner Pool] Fixed a bunch of bugs and refactored code

- android/app/build.gradle
You'll never be able to parse arbitrary Python code with a regex, but this should at least be a bit more flexible.
It still requires the version to be 3 numbers separated by dots, because it uses that to create the integer version code which Android uses internally.
> Make Android build script accept more syntax variations in version.py

- gui/qt/main_window.py
- lib/web.py
Some extended discussion on #952, combined with the new #1086 , suggests that we should add a new parameter to the uri scheme: **op_return_raw**
* the format is for `op_return_raw=<hex_string>`. The hex string decoded to binary then the byte 0x6a (OP_RETURN) is prefixed, resulting in the final scriptPubKey.
* For example, `op_return_raw=4c077361746f736869510101` results in the following scriptPubKey bytestring: `b'jL\x07satoshiQ\x01\x01'`, i.e., script `OP_RETURN OP_PUSHDATA1 0x07 'satoshi' OP_1 OP_PUSH1 '\x01'`
* Note this means the op_return_raw must include all relevant push opcodes, where desired. This can be used to make non-minimal pushes like the above example. Current bitcoin relay rules mean that op_return scripts must parse to a series of pushes but they need not be minimal.
* …
> raw opreturn in URIs

- contrib/update_checker/README.md
- contrib/update_checker/releases.json
- electron-cash
- gui/qt/__init__.py
- gui/qt/main_window.py
- gui/qt/network_dialog.py
- gui/qt/paytoedit.py
- gui/qt/update_checker.py
- ios/ElectronCash/electroncash_gui/ios_native/network_dialog.py
- ios/ElectronCash/electroncash_gui/ios_native/receive.py
- ios/ElectronCash/electroncash_gui/ios_native/send.py
- ios/make_ios_project.sh
- ios/recompile_python.sh
- lib/address.py
- lib/bitcoin.py
- lib/blockchain.py
- lib/keystore.py
- lib/network.py
- lib/networks.py
- lib/tests/test_bitcoin.py
- lib/verifier.py
- lib/version.py
- lib/wallet.py
- lib/web.py
- plugins/cosigner_pool/qt.py
This facility was inspired by a recent Electrum commit, and was also discussed in issue #1126 .
The purpose of this facility is merely as a convenience for users who aren't on reddit or aren't constantly refreshing our website to be able to find out when a new version is available.
It hopefully will decrease the number of users running very old versions of Electron Cash.
1. When the user selects "Check for updates...", Electron Cash connects to the URL hard-coded in `gui/qt/update_checker.py`. Currently: https://raw.github.com/Electron-Cash/Electron-Cash/master/contrib/update_checker/releases.json -- which is in this very repository!
2. It downloads `releases.json` 
3. It checks the versions seen in `releases.json` -- if they are newer than the version in the running app, and if the …
> [Qt] Update checker + Networks.py refactoring + Misc Nits and Cleanup

- gui/qt/main_window.py
- lib/keystore.py
I'm thinking it would be a good idea to add a note on sweep dialog like in this PR. This is in relation to #562 
(Not entirely sure about the placement of it, or the exact text. Please discuss.)
Besides in sweep, WIF private key import also happens with imported-privkey wallets but I think that's less of an issue and no warning needed there.
> add note about BIP38 keys on sweep dialog

- gui/qt/__init__.py
- gui/qt/exception_window.py
- gui/qt/main_window.py
- gui/qt/util.py
- lib/network.py
- lib/synchronizer.py
- lib/util.py
- lib/verifier.py
- lib/wallet.py
On window close the wallet stays open and continues to synchronize needlessly.  This is not expected UX.  It also is a waste of resources and slows down the app.  If you had several wallets open but then closed them the app would thus leak resources.
This has now been addressed in this PR.  Closing a wallet shuts down all of its resources, including removing all of its callbacks for subscriptions and cancelling all pending network sends from that wallet (they are tracked down based on callback method supplied to the request).
Since we can't "unsubscribe" from ElectrumX due to protocol limitations, we will get harmlessly notified on tx's in the network layer for a closed wallet, but the notifications are now ignored.
When we switch servers, the subscription set sent to a new server will …
> Fully close wallet + Many PyQt memory leaks fixed

- gui/qt/main_window.py
- lib/synchronizer.py
- lib/verifier.py
- lib/wallet.py
- Switching chains caused confusion of the wallet. We now re-verify any
new tx's when switching forks each time.
- We added some better locking
- I want to do away with the pruned_txo business. That's coming up next.
This commit also needs more testing and verification but for now it
seems to be an improvement over broken chain-switch and wallet getting
confused.
> Fixed a bunch of bugs in wallet

- gui/kivy/main_window.py
- gui/qt/main_window.py
- gui/qt/network_dialog.py
- gui/stdio.py
- gui/text.py
- ios/ElectronCash/app.py
- ios/ElectronCash/electroncash_gui/ios_native/gui.py
- lib/network.py
- lib/synchronizer.py
- lib/verifier.py
- lib/wallet.py
This is a much needed change.  The 'updated' callback was overloaded to
indicate the wallet history was updated as well as the blockchain was
updated.
This was too large a granularity for what we need.
Since the Qt gui can have multiple wallet windows open, this led to a
situation where the GUI wallet windows were updating themselves multiple
times per wallet that got a new history, even if the update didn't
concern their particular wallet.
So -- we split up the ambiguous 'updated' event into 'blockchain_updated'
and 'wallet_updated'.
blockchain_updated -- callbacks receive 2 ints a parameters (local_height,
server_height).  Usually they are equal but local_height may be larger
than server_height if the server we are connected to is lagging behind
other servers in terms of the latest …
> Network: 'updated' callback split into: 'wallet_updated' , 'blockchain_updated'

- gui/qt/main_window.py
- gui/qt/scan_beyond_gap.py
- lib/wallet.py
Addresses #1193 in a more user-friendly (and hopefully useful) manner.
To test this, create a testnet wallet using this xpub:
tpubD6NzVbkrYhZ4YRDtddy5nLmvdH7Qn6oR7euDpjqnZdniaJDTbaL17Gq86bsVNhKMkYwGvSvhamz5QkouzGJ4e2rkyHWbF5mHGX5Up377zBM
After the wallet synchs (it's a big wallet so be patient), you can use Wallet -> Scan beyond gap... and it should find 4 addresses past the gap limit (2 change and 2 receiving) which have a tx history, and it will add them to the wallet.
See a screenshot of it in action:
This option is obviously only enabled for deterministic wallets (watching-only & multisig tested and work).
> Addition of Wallet -> Scan beyond gap

- gui/qt/utxo_list.py
Code was throwing `AttributeError: 'NoneType' object has no attribute 'strip'`, if I right-clicked on empty space when a single item was selected.
New code based on address_list.py's menu function.
Same problem exists in shuffle plugin, FWIW
> fix utxo_list context menu

- contrib/make_secp
- lib/ecc_fast.py
- setup.py
`python3 setup.py sdist` now does 3 things automatically:
1. Runs `contrib/make_local`
2. Runs `contrib/make_packages`
3. Runs `contrib/make_secp`
And finally, as it always did before:
4. It does all the other stuff for building the `.tar.gz` and/or `.zip` 
The libseck256k1.so.0 library is bundled in the lib/ folder of Electron Cash.
Mac and Windows users will have to run the .dmg/.exe or build secp256k1 themselves using `contrib/make_secp`, of course.
> Add make_secp to python3 setup.py for bundling libseck256k1.so.0 

- lib/tests/test_bitcoin.py
This test failed after switching to Bitcoin ABC's libsecp.  Amaury Sechet explained it was likely due to differences in how the nonce is selected.
The test assumed signing always generates the exact same signed message, which is not always the case.
The revised test just verifies the thing can verify its own sigs, as well as a hard-coded (python ecdsa generated) signature.
> Fix failing test after switching to Bitcoin ABC libsecp

- gui/qt/address_list.py
- gui/qt/contact_list.py
- gui/qt/history_list.py
- gui/qt/request_list.py
- gui/qt/util.py
- gui/qt/utxo_list.py
Address list, History list, utxo list, contacts list, and request list
now all defer their updates if they are off-screen (isVisible() ==
False), to when they are next shown.  This drastically improves GUI
responsiveness on large wallets (with many addresses or a large history)
and also increases the speed of initial wallet synch since as the
address history changes, not as much redundant GUI refreshing happens.
Instead, the refreshes happen in the showEvent() (only if there are some deferred updates in the queue).
For most use cases of the GUI the net effect is a perception of a faster GUI. Absolute CPU time is reduced on wallet synch.
The only drawback is the first time you switch to a tab, if it has a heavy update() method, you may notice a delay that didn't occur before (you paid that …
> [Qt] Performance improvement for the 5 major tab widgets

- setup.py
This essentially adds an option to **not** build the `libsecp256k1.so` library by using the `--disable-secp` flag while running `python setup.py sdist`. The default is still to build the library, so the expected functionality hasn't changed. I also indented the edited class to fit the rest of the file.
This is useful for some build systems (specifically the Arch Linux AUR package for me), as:
* libsecp256k1 can be required as a dependency through the package manager, so it's redundant to build it again for Electron Cash
* The build for Arch Linux is currently being done from GitHub release tars rather than syncing the whole source tree, and `make_secp` requires the source tree.
> Option to disable libsecp256k1 build

- lib/caches.py
- lib/plot.py
Sometimes I like to run IPython in the electroncash repo directory and do things like `from lib import bitcoin`, just to play with the functions ... using relative imports makes sure this works.
> fix relative imports

- plugins/keepkey/qt_generic.py
- plugins/trezor/qt.py
- PIL is inferior to what Qt QImage can do.  So we nixed the PIL requirement for Trezor.
- Instead we are loading *any* image format Qt supports (which can be a very wide variety, including SVG, PNG, GIF, etc etc)
- We dither and scale the image to the required size, convert it to bitmap, invert it, and upload it to the Trezor as a 128x64 mono bmp.
- This facility is pretty cool.  You can load ANY image (even a color image) and it ends up looking ok on the final device with Qt's fast and good dithering algos.
- UI text has been updated to reflect this new capability
> [Trezor] Remove PIL dependency; any format Qt supports can be used for Homescreen

- gui/qt/utxo_list.py
- plugins/shuffle/client.py
- plugins/shuffle/coin_utils.py
- plugins/shuffle/qt.py
Right Click on a Shuffled coin in the coins tab (or a set of shuffled coins) and you get a new context menu option "Reshuffle Coin"
This allows you to increase privacy for yourself and/or provide liquidity for others by shuffling a coin that was already shuffled.
Rules/Caveats:
- The option sets and in-memory flag that is reset the next time the wallet is restarted -- so you can schedule a coin to be reshuffled but if you restart that coin will go back to the "Shuffled" status unconditionally
- If the shuffled coin happened to have another coin on that address, that coin will now be frozen after the shuffled coin is reshuffled.  The user will have to manually resolve the situation (if they unfreeze the coin typically it will just get queued for shuffling)
- It's possible to cancel a …
> CashShuffle: Implemented Coin -> Reshuffle

- plugins/ledger/auth2fa.py
- plugins/ledger/ledger.py
#749 seems to be stale, so I thought I'd fix it myself.
The code sets a flag if a HW.1 is connected and checks for version 1.0.4 specifically.
For other devices the newer version is checked as before.
> [WIP] Fix the support for Ledger HW1/Nano legacy hardware w/o touching Nano S/Blue

- lib/plugins.py
> Plugins DevMgr: Fix devices not being closed when their id is not in xpub_ids

- plugins/digitalbitbox/digitalbitbox.py
- plugins/ledger/ledger.py
Same problem as in #1129 exists with `ledger` and `digitalbitbox` plugins. Instead of using an assert this now uses `give_error` function with a proper error message.
> Hw Wallets: Show proper error message when trying to sign a tx with OP_RETURN

- contrib/osx/osx.spec
Removed a bunch of libs it turns out we don't need to make the generated Qt app smaller on OSX
> Thin generated OSX .app binary by removing un-needed Qt Libs

- contrib/build-wine/deterministic.spec
- contrib/build-wine/electron-cash.nsi
- lib/commands.py
- lib/daemon.py
Closes #1255 , Addresses #1253 . Also Closes #1259 .
- Also thin the windows binary a little by removing some unused libs (but ANGLE and SW rendering overall made it fatter)
- Adds the command-line option (windows only) -O/--qt_opengl which basically can be one of the accepted QT_OPENGL env vars: desktop, angle, software -- it will force Qt to try and use the specified mode (Qt by default is 'dynamic' and it tries to auto-detect a mode but some buggy windows drivers fail).
- Adds a shortcut to the windows installed version "Electron Cash (Software OpenGL)" which opens up electroncash with "--qt_opengl software"
- Adds some logic to warn if blowing away existing directory on install (#1259)
> Windows: Add missing opengl libs to support software rendering and ANGLE

- lib/servers.json
lots of people are getting
"the transaction was rejected by network rules.
66: insufficient priority"
when connected to this server -- they don't accept fees around ~1 sat/byte apparently
> take coinucopia off default servers list

- android/app/build.gradle
- contrib/deterministic-build/requirements-android.txt
The main requirements list should be shared cross-platform, otherwise we'll end up with unnecessary differences in behavior from one platform to another. The only thing that needs to be Android-specific is the binary wheels for pycryptodomex.
> Reduce Android-specific requirements file to just the binary wheels

- lib/web.py
blocktrail went offline 3/4/2019. remove from Preferences -> General -> Online Block Explorer
> removed defunct blocktrail.com explorers

- gui/qt/bip38_importer.py
- gui/qt/installwizard.py
- gui/qt/main_window.py
- lib/base_wizard.py
- lib/bitcoin.py
- lib/keystore.py
Closes issue #562 
It's hooked into 3 places in the UI:
- Sweep key dialog
- "Import private key" (Wallet menu for imported wallets)
- Install wizard -> Import private keys
The workflow is it detects the set of keys specified in the wizard/textedits and then for each key it prompts the user for a password. 
If the user lacks fast scrypt (either cryptodomex or hashlib.scrypt), this facility is disabled and electron cash behaves as before -- not acknowleding bip38 keys.
The sweep key dialog does display an error message if no scrypt -- telling the user to install cryptodomex.
See screenshot for normal operation of the dialog:
> Implemented BIP38 Key Importing

- contrib/base.sh
This patch removes the `GIT_REPO_ACCT` variable which is unused. It also allows to override `GIT_REPO` from environment, allowing a different git repository to be built. This way you can build a local repository for example with:
```
GIT_REPO=~/src/Electron-Cash ./contrib/build-wine/build.sh master
```
> Build: Allow overriding the github repository

- lib/util.py
When starting there is a console window shown for a split second on Windows because `fsutil` is called using `os.system`. This patch makes it use `subprocess.call` instead.
> Windows: Fix console flashing on startup

- plugins/ledger/auth2fa.py
- plugins/ledger/ledger.py
The service is not available anymore and the app has been removed from the Play store. This fixes the 2FA dialog for the Windows build as the websocket module is not included.
> Ledger: Remove non-working websocket 2FA for legacy ledger devices

- plugins/ledger/ledger.py
This is untested by me, but I don't see any reason why it wouldn't work.
> Ledger: Add Nano-X USB device ids

- gui/qt/console.py
Ctrl+Tab / Ctrl+Shift+Tab can be used to navigate the main window tabs, but as soon as the console is shown you can not switch to another tab. This is because the console consumes all tab key events, even those with modifiers. This patch makes the console ignore tab presses with modifier keys.
> Console: Only show completions when tab is pressed without modifier keys

- gui/qt/__init__.py
- lib/commands.py
To suppress certain warnings that can get annoying. For now we only make this affect the libsecp256k1 warning.
See #1297
> Commands: Add -R / --relax_warnings command line argument

- gui/qt/console.py
- gui/qt/main_window.py
This adds a semi transparent overlay over the console window, which must be acknowledged before the console can be interacted with. It warns the user of the dangers of entering code and requires them to type a string into a textbox to confirm they understand the risk. There is also a checkbox that can be used to remember this confirmation so it doesn't have to be done again for the loaded wallet.
closes #1297
This depends on #1305 & #1307, I will rebase when they are merged.
> Console: Add warning dialog to protect against social engineering attacks

- gui/qt/console.py
Follow up to #1308 
The focus policy that is restored to self.editor is wrong, the backup was made from self.
> Console: Restore correct focus policy

- gui/qt/console.py
This makes it more clear that the input box, button and checkbox are part of the warning, not of the window frame.
> Console: Make the margin of the warning around the layout

- gui/qt/main_window.py
For easier keyboard navigation. The & in the labels is in front of the key used as accelerator, you can press Alt+Key to use the accelerator, which makes focus jump to the labels buddy.
> Qt: Add accelerator keys to the Receive tab

- gui/qt/console.py
When the console was moved between screen boundaries with different scaling settings, the font was reset. This is because QPlainTextEdit sets the documents default font back to its own font property when Qt has a font change event. This patch sets the font property of the editor instead of the document.
closes #1314
> Console: Fix font reset when moving between screens

- gui/qt/address_list.py
The space is already added in the format. Also makes it just one translation string.
> Address List: Remove double space in balance column

- contrib/build-linux/appimage/_build.sh
- plugins/ledger/qt.py
There was an issue on some systems when loading the systems libusb caused by a bad interaction between PyQt5 and libusb. Check the individual commit messages to see what this PR addresses in detail.
> AppImage libusb / PyQt5 fix

- gui/qt/util.py
Consolas is the best monospace font on Windows and has been included by default starting with Windows 7
> Windows: Switch monospace font to Consolas

- lib/ecc_fast.py
- lib/schnorr.py
- lib/secp256k1.py
- lib/transaction.py
Note -- this is a continuation of Jonadl's PR so that he gets commit credits too, because I know he really wants them.
Phase 1:
- Refactored libsecp-related setup into its own file: `secp256k1.py`. If libsecp256k1 is successfully loaded, an app-global context is created that various dependent modules can utilize.
- The loaded lib is accessed as: `secp256k1.secp256k1` (if loaded successfully), or is None otherwise
- `ecc_fast.py` depends on this, and uses the above facility now.  It itself does no library loading. 
- `schnorr.py` also uses the aforementioned facility now.
`schnorr.py` has been massiely refactored from Jonald's commit.  It has ~~a single useful function~~ ~~two~~ three useful functions right now: `schnorr.sign`, `schnorr.verify` and `schnorr.is_available`.
- Got rid of all …
> Schnorr Redux

- lib/schnorr.py
- lib/transaction.py
This is a basic integration between the Schnorr library and the transaction layer in the wallet.  Hopefully I didn't make too many awful mistakes.  The schnorr code was unit tested with one of Mark's test examples.
Currently the code is in a dormant state and must be turned on by a developer to be used.
> Add Basic Schnorr Capability For Transactions with secp256k1

- lib/schnorr.py
This is a fallback if secp256k1 library is not available for whatever reason.
For reference, see verification and signing sections here: https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki#verification
Also changes failure mode API (return vs exception) somewhat.
> Add pure python schnorr

- gui/qt/main_window.py
- gui/qt/transaction_dialog.py
- lib/coinchooser.py
- lib/transaction.py
- lib/wallet.py
Off by default. Can be enabled in prefs.  Only transactions signed from the UI will use Schnorr if enabled.
It is enabled on a per-wallet basis.
CashShuffle is unaffected (all CashShuffle tx's will continue to use ECDSA, as per CashShuffle spec).
In prefs screen:
Disabled for multisig or hardware wallets:
Disabled for systems lacking libsecp or libsecp + Schnorr:
This is what it looks like when you sign a tx:
> Add Schnorr signature capability to the UI

- gui/qt/main_window.py
- gui/qt/udev_installer.py
Writes a temporary script to perform the actions and runs it elevated using the first usable of pkexec, gksudo and kdesudo.
The hardware ids are queried from the device manager.
> Linux: Add helper dialog to install udev rules

- gui/qt/udev_installer.py
There might be some freak configurations where root umask makes udev files writable by others by default. That would be bad as udev rules can execute commands. This patch explicitly sets the umask and also adds set +e to the script to let any errors propagate.
> Linux: Explicitly set umask when creating udev rules

- lib/tests/test_transaction.py
- lib/transaction.py
- plugins/trezor/trezor.py
The previous incarnation of this function was really really fragile/broken/dumb.
This one actually updates signatures without relying on the fragile (and not working for multisig) "scritpSig" hack we use to serialize metadata into the tx.
This is inspired by Electrum's approach (after reading their code) but independently developed  to be a little leaner and meaner.
> [Lib] Fixed Transaction update_signatures to actually work w/ multisig

- plugins/keepkey/keepkey.py
The KeepKey firmware does not understand CashAddr testnet addresses.
> KeepKey: Add support for testnet using legacy address format

- plugins/keepkey/keepkey.py
The last commit was not enough as keepkey produces wrong signatures.
Instead, we now always use mainnet address format.
Also we always use cashaddr as legacy addresses are not compatible.
> KeepKey: Fix testnet support

- contrib/build-linux/appimage/Dockerfile_ub1404
- contrib/build-linux/appimage/_build.sh
- contrib/build-wine/_build.sh
- contrib/make_secp
- contrib/make_zbar
- lib/qrscanner.py
- setup.py
Zbar master includes various fixes for Windows as well as DirectShow support. We should update this to 0.23 as soon as it is released.
The patch also adds a reproducible build of zbar for Linux.
> Zbar: Bump to upstream master and add Linux build

- contrib/build-linux/appimage/_build.sh
See the individual commits for explanations. Note that our AppImages are still not reproducible, even though the contents are always the same after this commit. This is due to AppImageKit needing more fixes:
https://github.com/AppImage/AppImageKit/issues/929
> AppImage: build fixes

- plugins/ledger/ledger.py
plugins/ledger/ledger.py:291: warning: internationalized messages should not contain the '\r' escape sequence
> Ledger: Fix warning about \r in translation message

- lib/network.py
In anticipation of new txindex https://reviews.bitcoinabc.org/D2924
(RPC error message includes 'no such' so without this it will trigger the next condition)
> add error message for still-indexing server

- lib/transaction.py
- plugins/digitalbitbox/digitalbitbox.py
- plugins/ledger/ledger.py
- plugins/shuffle/coin_utils.py
This doesn't make sense as a transaction property, and many places were calling this assuming that it would always return 0x41.
Also we don't support serializing sighash for other than 0x41 right now,
so I put in a sanity check.
(and tried a shuffle; this works =D)
> refactor nHashType

- contrib/build-wine/_build.sh
This is not needed anymore as we now use Qt to get video data from the camera.
> Zbar: Disable video support for Windows build

- contrib/build-linux/appimage/Dockerfile_ub1404
As we don't need video support in Zbar anymore we can remove some of the dependencies.
> AppImage: Clean up dependencies of the Docker image

- gui/qt/main_window.py
- lib/coinchooser.py
- lib/transaction.py
- lib/wallet.py
- plugins/digitalbitbox/digitalbitbox.py
By adding this to the unsigned coins (unsigned input dicts) we get a
finer grained control over which inputs are signed which way.
Overall less passing around of the `sign_schnorr` parameter, too.
> Refactor sign_schnorr tx generation mechanics to be per-input

- gui/qt/main_window.py
- gui/qt/qrreaderutil.py
- gui/qt/qrtextedit.py
Disable QR reader for older verisons of Qt5. Show an error box when
attempting to use QR reader instead.
> Support older versions of Qt5

- lib/address.py
- lib/transaction.py
How this can occur:
- P2PK with pubkey of wrong length / prefixbyte
- P2PKH with wrong length hash
- P2SH with wrong length hash
- exceptions from script_GetOp if any (e.g., due to truncated scripts. Not right now but code may become more strict.).
In all cases it's safe to just fail to ScriptOutput.
testnet example I crafted (p2pkh with 19 bytes): f94324c9a21bef97feaead5bd2e96ba2ef3775aaa4b00d7c2c15dd564684921a
(also, fix a couple of nits: should never use BaseException, and give helpful exception message)
> Gracefully fail when standard output script type parser throws exception

- plugins/ledger/ledger.py
When trying to pair a Ledger which is not in any app but in the main screen for selecting applications it responds to the "GET FIRMWARE VERSION" ADPU with code 0x6700. We use that call to check if we have a connection to the device in has_usable_connection_with_device. This causes the check to fail and the device manager will mark the device as disconnected right after registering it. This will cause the message "'NoneType' object has no attribute 'handler'" being shown when attempting to pair.
Instead of just assuming our connection is dead when we get code 0x6700 back this patch makes it ignore that specific status. It might make sense here to ignore all status code returns of the Ledger as even
getting a status code back means we have a connection.
As a result of this patch we now …
> Ledger: Fix error message when BCH app is not active

- lib/address.py
- lib/transaction.py
- plugins/hw_wallet/plugin.py
To follow up from #829 and #1396, this cleans up the way that scripts are parsed.
- deduplicate effort in transaction.py/address.py, in favour of the more strict `Script.get_ops` in address.py
- make a nicer parse result in `Script.get_ops`
A couple of test txns to do load from blockchain:
9969603dca74d14d29d1d5f56b94c7872551607f8c2d6837ab9715c60721b50e (script output, to see decompilation)
ebc9fa1196a59e192352d76c0f6e73167046b9d37b8302b6bb6968dfd279b767 (invalid scripts on output)
> Script parser cleanup

- gui/qt/main_window.py
- gui/qt/paytoedit.py
- Kicks-in only if pay to field reads like `cointext:phone_number`, otherwise normal call path is followed.
- Is slightly hacky -- but it's the best we can do: it intercepts the  Send/Preview button and then does an asynchronous request to the CoinText server, to retrieve the signed PR.
- The Send tab then goes into "Payment Request" mode where they get another chance to review the tx. The send tab is transformed with the final payment info -- including **amount** which *comes from the server*, hence why it **must** be reviewed again by the user.
- At this point it just works like a normal payment request.
> Implement CoinText

- lib/schnorr.py
Python is genius because you can include pseudocode like this, and only
throws an exception when it needs to remind the programmer that they didn't
finish the implementation!
Pseudocode from https://tools.ietf.org/html/rfc6979#page-12
```
K = HMAC_K(V || 0x00)
V = HMAC_K(V)
and loop (try to generate a new T, and so on).
```
(this code only has a 2^-128 chance of running, I only noticed because I re-read it)
> implement hmac pseudocode

- contrib/submit_av.sh
For the script to work you need to set your API keys in the VIRUSTOTAL_API_KEY and METADEFENDER_API_KEY environment variables.
Just call like this, for example:
```
./contrib/submit_av.sh dist/*.exe
```
> Add script to automate submission to VirusTotal and MetaDefender

- gui/qt/__init__.py
- lib/commands.py
Enables automatic DPI scaling on Windows and Linux and enables high DPI pixmaps on all platforms.
There is a command line option that can be used to disable automatic DPI scaling called `--qt_disable_highdpi`. This can be used in cases where unwanted scaling happens, like small displays or displays with bad EDID information.
> Qt: High DPI support

- gui/qt/utils/aspect_svg_widget.py
- plugins/shuffle/qt.py
FixedAspectRatioSvgWidget takes a width and returns a size hint with that width and a height that matches the aspect ratio of the loaded SVG file.
This also makes the CashShuffle logo rendered using this instead of caching a pixmap which fails on multi monitor DPI changes.
> High DPI: Add new fixed aspect ratio SVG widget

- lib/servers.json
Added: 
bch.soul-dev.com 
electrumx-cash.1209k.com 
bch.loping.net 
bchx.disdev.org 
electrum-abc.criptolayer.net 
Removed for unresponsive: 
leblancnet
curalle.ovh
Updated versions and ports
> Update servers list

- gui/qt/main_window.py
Catch just ImportError, of which ModuleNotFoundError is a subclass.
closes #1430
> Settings: Remove ModuleNotFoundError as it is Python 3.6+

- gui/qt/paytoedit.py
- lib/contacts.py
This changes the OpenAlias prefix to 'bch' instead of 'btc'. The OpenAlias website says there is no need to register prefixes at the moment.
This also fixes some code rot that prevented OpenAlias from working, specifically the TXT record not being decoded into a string, the PayToEdit not handling returned Address objects.
closes #1441
> OpenAlias: Change prefix and fix code rot

- contrib/build-linux/appimage/_build.sh
- contrib/build-linux/appimage/patches/python-3.6.8-reproducible-buildinfo.diff
follow up to #1444 
There was a problem where Python would not properly include the faketime timestamp sometimes. This patch replaces faketime with a patch that is used by Ubuntu for reproducible builds by exporting BUILD_DATE and BUILD_TIME with the desired values.
> AppImage: Improve reproducible Python build reliability on Linux

- gui/qt/address_list.py
- gui/qt/contact_list.py
- gui/qt/history_list.py
- gui/qt/main_window.py
- gui/qt/util.py
There was an issue where `webbrowser.open` would invoke a program like `kde-open5` that loaded the systems `libQt5DBus`, which was not satisfied with the AppImage's `libdbus`. To fix this we fork the
process, unset `LD_LIBRARY_PATH` and then open the URL.
See https://github.com/spesmilo/electrum/issues/5425
> AppImage: Fix webbrowser.open not opening links

- contrib/build-wine/_build.sh
- contrib/requirements/requirements-wine-build.txt
For this we use a PyInstaller that has the `windres` bug fixed and we set `gcc` to ignore the `strncpy` errors in the bootloader.
This results in a smaller binary that gets much less detections by anti-virus programs. The binary dynamically links `msvcrt.dll`, but that binary is available by default on every system we support.
See https://github.com/EchterAgo/pyinstaller/commit/d1cdd726d6a9edc70150d5302453fb90fdd09bf2
> PyInstaller: Rebuild bootloader from source using MinGW

- lib/transaction.py
- all bitcoin txes must have at least 1 output; this is a consensus rule.
- don't ignore garbage after transaction ends.
`can_read_more` function borrowed from https://github.com/spesmilo/electrum/commit/71ce7cce6d
Adopting stricter rules makes it less likely for SPV verifier to hit a `InnerNodeOfSpvProofIsValidTx` error.
> improve transaction deserialization strictness

- gui/qt/main_window.py
The video device would show empty instead of "Default" when the user never set a video device. This was a display issue only, it would still use the default camera even if it was empty.
> Preferences: Fix empty video device when value hasn't been set

- contrib/build-linux/appimage/_build.sh
There are a lot of dupliacted files, testing files and unused libraries present in the AppImage. Removing these reduces the AppImage size significantly.
0be65ec5b94f7a8b0a6024dd55ea2f573dc6aa77853d0c3038b837a8d0923d70  dist/Electron-Cash-4.0.7-dev4-4-gcff5fb1-x86_64.AppImage
File size is reduced to 46MB
> AppImage: Remove unused binaries and some redundant build commands

- contrib/build-wine/_build.sh
This will speed up the build as only the specific revision that we pinned will be cloned. This reduces the amount of data transferred from over 30MB to just over 2MB.
> PyInstaller: Shallow clone the repository

- gui/qt/main_window.py
- lib/i18n.py
- lib/utils/macos.py
- lib/utils/unicode_tools.py
- setup.py
When the user has not chosen a language we now use the system language or its best match by default. This takes care of selecting for example es_AR as the preferred match for Spanish.
In the dialog we now show the language name translated to that language and we include the language code in monospace as a prefix to help sorting.
We move the General tab to the first position of the settings dialog which makes it slightly easier to find the language setting in case the UI is in the wrong language.
Finally we forgot to include 8 languages that are on Crowdin but not in the GUI (Bulgarian, Mexican, Farsi, Korean, Swedish, Turkish, Ukranian and Traditional Chinese)
> Localization: Default to system language and improve dialog

- plugins/ledger/ledger.py
The code used output both as a loop variable and as a regular variable to pass the output to the 2FA function. This broke with multiple outputs.
closes #1478
> Ledger: Fix 2FA dialog with Legacy devices and multiple outputs

- contrib/build-linux/appimage/Dockerfile_ub1604
- contrib/build-linux/appimage/_build.sh
- contrib/build-linux/appimage/apprun.sh
- contrib/build-linux/appimage/test-freetype.py
This makes it possible to support color emojis even on Ubuntu 14.04.
Please merge #1489, #1490 & #1491 first and then I'll rebase this.
> AppImage: Make color emojis available on more platforms

- gui/qt/transaction_dialog.py
- lib/i18n.py
- lib/wallet.py
We add an ngettext function to the i18n module and change some translation strings to use it. This also improves some translation strings.
> Translations: Add support for plural forms

- plugins/ledger/ledger.py
This was accidentally broken in 1e5aaf6a9f2863b5978923ae4d24a49d0f6684fe
We removed the `output` variable to fix the 2FA dialog but missed that the OP_RETURN code path was still using it.
> Ledger: Fix OP_RETURN data causing exception

- lib/transaction.py
- lib/verifier.py
In #1457, the transaction deserializer was restricted for the sake of the
merkle node checker, however I realized that the merkle node checker can
do strict checks on its own, and the transaction deserializer can be
liberal which may be useful for smart contracts (e.g., crowd funds using
ANYONECANPAY that start out with 0 inputs).
Besides that advantage, this also further strictifies the merkle node checker
so its false positive rate is 1 million times lower.
Reviewers: please examine for runtime errors since this code runs
**extremely** infrequently: the txin, and txout, lines only get passed by
1 in a billion transactions. A runtime error will simply be ignored here,
but unfortunately this disables the point of this code.
> Liberalize transaction deserializer and restrict merkle node checker.

- lib/verifier.py
I just realized, I had a brainfart in #1506 : for coinbases there is actually no restriction on the prevout_n, rather it is just a *convention* to set it to 0xffffffff. Fortunately, we can still make use of the prevout_n range idea, since coinbases have another very distinguishing feature.
Reference:
https://github.com/Bitcoin-ABC/bitcoin-abc/blob/2f1adeefb67e985757cfae62b40c2edc5011b742/src/consensus/tx_verify.cpp#L233-L250
https://github.com/Bitcoin-ABC/bitcoin-abc/blob/2f1adeefb67e985757cfae62b40c2edc5011b742/src/primitives/transaction.h#L281-L283
> merkle node checker fixup

- README.rst
- gui/qt/__init__.py
see #1436
I got this missing dependency on a fairly fresh install of Xubuntu 19.04
> More help for "QtSvg Missing" error

- plugins/digitalbitbox/digitalbitbox.py
the check seems to prevent op_return transactions.
> Remove address output requirement for bitbox

- plugins/hw_wallet/plugin.py
- plugins/keepkey/keepkey.py
- plugins/ledger/ledger.py
Hopefully we can use this function to support OP_RETURNs with more than
1 pushdata (such as Cash Accounts).
This function is now generalized to verify the script for the number of
pushdatas that the caller expects (defaults to 1).
> HW wallets: Generalize the validate_op_return_output_and_get_data

- gui/qt/address_list.py
- gui/qt/cashacctqt.py
- gui/qt/contact_list.py
- gui/qt/main_window.py
- gui/qt/transaction_dialog.py
- lib/cashacct.py
And all fields that accept cash accounts "accept" the emoji char if at
the end (it is stripped out internally and not used).
This makes it easier to eg copy/paste your cash account into a message,
Slack, Telegram, etc when giving it out.
Eg: "VoidPointer#26710; 🍌"
I'd like to know what people think of this -- not sure if we want to do this but it does make it easier to give out your cash account + emoji .. and does no harm.
I talked to Pokkst (the other wallet dev that has a wallet that supports Cash Accounts) and he says pasting such a string into his wallet will work (will do no harm).
So -- request for comments!
> CashAccounts: Make all "copy" operations in app append the emoji char

- lib/servers.json
- lib/servers_testnet.json
- plugins/shuffle/servers.json
I have added a TOR service for electroncash.de
cashshuffle.net and the .onion service is currently configured as a 7 player shuffle server
> Add TOR service for electroncash.de & cashshuffle server

- gui/qt/address_list.py
- gui/qt/contact_list.py
- gui/qt/main_window.py
- gui/qt/utxo_list.py
Closes #1531 
In particular the cashaddr_toggled_signal was connected to objects that
were since deleted. According to Qt (and PyQt) documentation the
connections should get auto-reaped.  But Axel Gember was getting
"Wrapped C++ object deleted" exceptions (#1531) related to this signal still
firing on deleted slots -- very rarely.
As a safety measure, we are now explicitly disconnecting this signal during window close
for objects that connect to the global gui_object.cashaddr_toggled_signal, as well as other associated signals.
This level of paranoia shouldn't be necessary but we did get a crash report -- and according to the API docs the impossible happened.  Hence this patch.
> Qt GUI Fix: On Python 3.7.3, PyQt5 5.12.3+, signals not cleaned up

- gui/qt/fee_slider.py
- gui/qt/invoice_list.py
- gui/qt/main_window.py
- gui/qt/request_list.py
- gui/qt/util.py
- lib/util.py
- lib/wallet.py
Some strings get translated before the actual translation files are loaded. This patch changes it to use deferred translation as described in:
https://docs.python.org/3/library/gettext.html#deferred-translations
This finally makes the transaction status, request expiry and payment request tooltips translatable.
> Translation: Defer translation lookup of some strings

- gui/qt/data/fonts.xml
There were issues with font fallback at least on Arch Cinnamon and on a Debian 9 I've been using in Qubes. The new fonts.xml should be more safe, but also the user might need to install the Bitstream Vera font to work optimally. This is because we blacklist the DejaVu font because it includes bad emojis and the Bitstream Vera font is essentially DejaVu without the emojis.
> Fonts: Use a more safe fontconfig override

- contrib/base.sh
- contrib/build-linux/appimage/_build.sh
Umask seems to leak into Docker containers and causes the build to not be reproducible accross different umasks.
> Build: Set a fixed umask before starting Docker

- gui/qt/__init__.py
- gui/qt/main_window.py
- lib/simple_config.py
Changes to status quo:
Windows:
- Enables FreeType on Windows by default only iff Windows version < Windows 10
- The above can be overridden by a new Preferences setting ("Enable FreeType for font rendering")
Linux:
- Added some paranoia checks when deciding to override fontconfig with FONTCONFIG_FILE
- Made the FONTCONFIG_FILE override entirely preference-overridable (see Prefs) (default enabled)
> Windows & Linux - FreeType & fontconfig logic tweaks + prefs options

- lib/networks.py
Until #1540 is fixed, this is necessary to give an acceptable new user experience in the Android app.
> Update blockchain checkpoint

- contrib/build-wine/electron-cash.nsi
- contrib/osx/make_osx
- electron-cash
- electron-cash.desktop
- gui/qt/main_window.py
- gui/qt/paytoedit.py
- lib/cashacct.py
- lib/web.py
- org.electroncash.ElectronCash.appdata.xml
This involved the minimal possible changes:
- electron-cash script accepts `cashacct:` URIs
- PayToEdit knows how to deal with them
- Main window pay_to_URI modified
- web.parse_URI can parse them
- web.create_URI can create them
Added desktop integration for `cashacct:` URL type
- macOS Info.plist
- Windows setup.exe .nsi installer
- Linux .desktop file (AppImage, etc)
> CashAccounts: Added parsing & integration of cashacct: URIs

- gui/qt/main_window.py
Here is how to reproduce the crash (Linux & Windows):
---
- Start up a wallet
- Double-click a tx
- Close tx dialog
- Open up preferences within a few seconds (can use `Ctrl+,` hotkey or the StatusButton -- does not matter)
There is a 90% chance it will crash.  The stack trace is it crashing in a `free()` call in the C lib from a `QDialog` destructor, which is misleading.
Update: This is on Linux Ubuntu 18.04 & Windows 10 using Python 3.6.8, running form source, with PyQt5 5.12.3 -- Windows 10 is using 32-bit Python and Linux is 64-bit; the crashes also happen when building an AppImage or Windows .exe, however.
Update 2: Also crashes on Ubuntu 18.04 with Python 3.7.3 using the requirements from contrib/ installed.
---
This is the stack trace on Windows:
```
1  PyInit_sip …
```
> Linux & Windows: Fix for Preferences crash caused by lazy-loading QtMultimedia

- contrib/build-linux/appimage/build.sh
- contrib/build-linux/srcdist_docker/build.sh
- contrib/build-wine/build.sh
This enables the usage of the build scripts for users that do not require sudo to execute the docker command.
> Build: Only set SUDO if it is not defined already

- contrib/base.sh
- contrib/build-linux/appimage/build.sh
- contrib/build-linux/srcdist_docker/Dockerfile
- contrib/build-linux/srcdist_docker/_build.sh
- contrib/build-linux/srcdist_docker/build.sh
- contrib/build-wine/_build.sh
- contrib/build-wine/build.sh
- contrib/build-wine/docker/Dockerfile
- contrib/build-wine/electron-cash.nsi
- contrib/make_linux_sdist
- setup.py
* Adds PYI_SKIP_TAG, which can be set to 1 to skip PyInstaller boot loader tagging. This can be useful to compare binary output across different revisions.
* Remove version included in PyInstaller name. This caused builds to not be comparable across different revisions.
* Correctly handle stdin/out not being a TTY. Output will be logfile friendly.
* Run as current user inside docker. This will prevent root-owned files being created in the source directory.
* Show SHA256 sums and file sizes at end of Wine build.
> Build: Improvements for automatic builds and reproducibility

- gui/qt/transaction_dialog.py
- gui/qt/util.py
Previously entering the input/output list always caused a text cursor to be visible. This changes it so the cursor will only be visible when entering the control using the keyboard or pressing keys when it is focused.
> TxDialog: Improve in/outputs text-selection behaviour

- gui/qt/main_window.py
- lib/paymentrequest.py
- lib/web.py
This replaces BIP70 for "*.bitpay.com" on https *only*.
Apparently BitPay prefers we use this different API for payment
requests. It still presents us with some challenges in that it relies on
PGP ultimately to verify sigs.
For now we disable their bizarre key verification scheme and just
rely on SSL verification which is very secure against MITM.
I am waiting to hear back from BitPay if it's ok to hard-code bitcoin
keys in our app, since we'd rather not rely on PGP.
But for now, SSL verification is very good, so we rely on that for
BitPay 2.0.
I won't merge this just yet. I need to first make sure this doesn't break Android and iOS. The external API for these type payment requests is identical, more or less.  The only change is the pr.raw field which now is a more complex object for the …
> Payment Requests: Added BitPay 2.0 JSON API

- gui/qt/transaction_dialog.py
- lib/wallet.py
follow-on from #1499
ngettext takes care of the number delegation which can vary greatly
depending on language (there can be multiple plural forms!), and .format
is fine with having unused keyword args.
also clean up one other instance with intermediate variable to match
rest of codebase.
To test this, try Tools | Load Transaction | From Text with: `00000000000000000000` (0 inputs and 0 outputs) in English locale; observe it no longer says "Inputs ({num_inputs})" and "Outputs ({num_outputs})" just above the list fields.
> clean up ngettext().format()

- contrib/build-wine/_build.sh
This version merged our code changes for partial composite device opening and should work for KeepKey and Trezor.
> Windows: Switch libusb to version 1.0.23-rc2

- lib/schnorr.py
- lib/secp256k1.py
- lib/tests/test_schnorr.py
The BlindSignatureRequest class lets you request blinded Schnorr
signatures, and then upon completion, unblind them.
There is also a functional and secure BlindSigner class, though see the
caveats in the docstring.
The resultant signatures are fully valid with respect to the BCH Schnorr
signature convention. So, you could in principle use them for transaction
signatures or CHECKDATASIG signatures. Or, just use them in off-chain
protocols like Cash Fusion.
> add blind signature mechanism to schnorr.py

- gui/qt/console.py
Back we initially added the console warning, we didn't do automatic high DPI scaling except on macOS. Enabling the scaling caused the console warning to be too large for the default window size on Windows and Linux.
This just reduces the padding / margins a bit, decreases the font size and keeps the Wikipedia link in the same paragraph.
> Console: Make warning fit in default window size

- gui/qt/console.py
fixes the warning output -
```QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 16, 120, 16, 215'```
```QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 200, 220, 200, 215'```
> specify alpha value (rgba color)

- lib/bitcoin.py
- lib/tests/test_bitcoin.py
- tox.ini
After conversations in telegram, it became clear we need this facility to produce paper wallets (Licho is working on a paper wallet plugin).  We also need it to perhaps offer a GUI option to "Expirt WIF to Bip38" or some such.
This was implemented last night by me from reading the spec here:
https://github.com/bitcoin/bips/blob/master/bip-0038.mediawiki
Supports producing both "EC Mult" and regular "Non EC Mult" keys. 
Unit tests included -- all tests pass.
(Note that the `tox` test suite now requires `pycryptodomex` -- which shouldn't be a problem.)
> Add Bip38 encryption capability to the class bitcoin.Bip38Key

- gui/qt/main_window.py
- gui/qt/password_dialog.py
- Wallet -> Private Keys -> Export -> BIP38 Encrypted...; prompts user for passphrase, exports all keys encrypted with said passphrase.
- In Private key dialog (accessible from address right-click menu), added a "Encrypt BIP38..." button which prompts for passphrase and encrypts the displayed WIF key using BIP38
Also in this PR:
- GUI nits: Made all menubar menus follow the UI standard "**Thing...**" if "**Thing**" leads to a dialog box.
- Added password dialog box checkbox "Show" which shows the password the user is inputting. This is a standard GUI thing to do since some users prefer to see what they are typing. Off by default.
> Add BIP38 Encryption to the GUI

- gui/qt/main_window.py
- ios/ElectronCash/electroncash_gui/ios_native/gui.py
Apparently, we were doing it wrong. Read this relevant section:
https://github.com/bitcoin/bips/blob/master/bip-0070.mediawiki#Payment
it makes me nervous to do it this way though. Also -- I prefer asking the merchant for ACK first before broadcasting (spec seems to indicate you broadcast THEN ask merchant for ACK).
Seems strange to me.  Requesting review and comment from people, otherwise I won't change it.
> Implement BIP70 properly on Qt and iOS

- lib/paymentrequest.py
Allows EC payment requests to be accepted by other wallets that support BIP70 (bitcoin.com) by setting the payment_details_version of the request. E.g. previously bitcoin.com (bitcore-payment-protocol) considered these requests to have 'Invalid Protocol'.
> BIP70 Payment Request Fix

- lib/wallet.py
Adding the ID as a suffix to the payment_url will allow users to create a payment_url that is identical to request_url and therefore maintain compatibility with bitcoin.com wallet which currently ignores payment_url from the Payment Request and uses request_url instead.
> Configure payment_url to include payment request ID

- plugins/shuffle/servers.json
Shutting down cashshuffle.net server, activity on CashShuffle is 100% on shuffle.servo.cash
I can always create a new one
> Removed cashshuffle.net

- lib/wallet.py
This closes #895.
Below is a screenshot of the exact same wallet mentioned in #895; a watching-only wallet off the p2sh address: `bitcoincash:pqt79ay4h05q2dk889wn28l66942mgrtgqa7jjqt3h`.  Note how it now has the correct balance and it detected the spends of the coins correctly (whereas previously it did not).
---
**Note:** An additional wallet one can try is watching-only over one of the May hard-fork attacker's addresses: `bitcoincash:pz3y5uvukandk0h3yvut2zsua9gp2tknf5nwnue2tj`
---
This PR fixes the coin tracking when the scriptSig / redeemScript is not what the wallet was expecting. Previously, `add_transaction` would *solely* rely on the heuristic parsing of the scriptSig to track coin spends (eg `txin['address']`). This works 99% of the time but if one wants to do something fancy …
> p2sh: Fix coin tracking / balance, etc for esoteric scriptSigs/redeemScripts in inputs

- android/app/src/main/python/electroncash_gui/android/console.py
With the new version of Chaquopy, Python files are pre-compiled, so their names no longer end with ".py".
> Fix Android console unit_test function

- contrib/make_locale
- gui/qt/main_window.py
- gui/qt/network_dialog.py
- gui/qt/transaction_dialog.py
- ios/ElectronCash/electroncash_gui/ios_native/network_dialog.py
- ios/ElectronCash/electroncash_gui/ios_native/prefs.py
- ios/ElectronCash/electroncash_gui/ios_native/wallets.py
- lib/i18n.py
Some words need additional context to be correctly translated, like in the case of the current "None" translation string. For example in German you need to know the gender of what is referenced to correctly translate it. This is different in different parts of the UI and we previously used the wrong form in some places.
Context will allow us to have multiple tranlsations of the same words depending on where they are used.
In gettext, pgettext and similar functions would be used for this. Sadly Python only added these in version 3.8. To support them with lower Python versions, we take advantage of those versions not being aware that the separator of msgctxt and msgid is \x04 and look up a msgid that is combined with the msgctxt.
This also changes a few places to use pgettext for more …
> i18n: Add support for pgettext and npgettext with msgctxt

- lib/commands.py
- lib/wallet.py
Normally addrequest will only generate a url for a static page using GET
request key/value format (e.g. mydomain.com/index.html?id=abcdefghij).
By adding the --index_url option to addrequest, users can override this
format and specify the url they want to use for displaying BIP70 payment
requests.
> Add index_url override to addrequest command

- gui/qt/main_window.py
Various fixes in the menus;
* move the 'Delete' from 'file' to 'wallet'. As this is about the
current wallet, not a file.
* Fix the ampersants usage, removing duplicates and adding some obvious
shortcuts. (for clarity, this is for keyboard navigation using 'Alt').
* Fix usage of elipsis (...).
Any menu item that takes an action is potentially dangerous to click.
To make clear that some menu options do not in actual fact take immediate
action, but show a dialog you can still escape, then we add the ... to a
menu item.  This commit fixes all the menu items to do this properly.
* Small consistency fixes in title-casing (there should be none in the
preferences dialog)
* Move 'Ctrl-Q' to become a visible shortcut for Quit.
> Menu UX fixes

- gui/qt/address_list.py
- lib/wallet.py
Also, pop open the (now shorter) change address list by default, and fix a bug.
> Addresses tab: hide all empty change addrs, not just used ones

- .gitignore
- lib/commands.py
- lib/mnemonic.py
- lib/simple_config.py
- lib/tests/test_wallet.py
- lib/wallet.py
- setup.py
This pull request adds ability to use create and restore from RPC.
This is mostly a backport(with some fixes specific to electron cash) from electrum to electron cash.
Also I made PyQt5 not a mandatory requirement, so to install pyqt5 too, you would need
`pip install .[full]` or `pip install .[gui]`
Binary building might be adjusted to include this dependency.
I have also fixed some issues I met when adding this functionality.
Tests are for that are added too.
> Added create/restore functionality in RPC, fixes

- ios/CustomCode/CWStatusBarNotification/CWStatusBarNotification.h
- ios/CustomCode/CWStatusBarNotification/CWStatusBarNotification.m
- ios/ElectronCash/electroncash_gui/ios_native/appdelegate.py
- ios/ElectronCash/electroncash_gui/ios_native/gui.py
- ios/ElectronCash/electroncash_gui/ios_native/send.py
- ios/ElectronCash/electroncash_gui/ios_native/utils.py
This PR concerns the iOS version only. It includes:
- A fix for the iOS 13.0 "Status Bar" glitch whereby the status bar cannot be drawn over by a UIWindow or UIView (previous iOS versions allowed this).  Our notifications would appear in this area; so a workaround was needed if on iPhone < iPhoneX and if on iOS > 13 when displaying a notification.  (On iPad the workaround would have been too complex so we just unconditionally hide the status bar on iPads.. which is fine since they can always run the app in windowed mode.)
- This PR also fixed an issue with the "Downloading headers XX%..." notification not calculating the percentage in a UX-useful manner.
- This PR also has random small nits/fixes/dead code removal for iOS only.
Note that the real fix to this is to use a different in-app …
> iOS: Fixes for iOS 13.0+ and other miscellany

- README.rst
During a recent fresh install it seemed some development version instructions were out of date, or missing.
> update README for development version

- contrib/build-linux/appimage/_build.sh
Slightly reduces file size, improves build speed and makes build more reproducible.
The `.comment` section contained GCC version information which could cause different build output from just a minor update in GCC. The information is not needed so we `strip` this.
The strip command was invoked using `xargs`, spawning a new process for each file. This is inefficient as `xargs` can correctly run the `strip` command with multiple file names.
> AppImage: Improve binary stripping

- lib/web.py
Recently I was looking for more testnet explorers to add to EC and came across [BlockExplorer.one](https://blockexplorer.one/). I got their permission to use the explorer in EC. They are planning on adding a page listing the services/wallets that use their explorer and want to add EC there. Is this OK @fyookball ?
> Add BlockExplorer.one explorer

- contrib/build-wine/_build.sh
- plugins/satochip/CardConnector.py
- plugins/satochip/satochip.py
Minor changes: reduced smartcard timout and updated satochip version
A timeout of 0.1s is sufficient if the card reader is connected and the card is already inserted. Otherwise, the card is not detected and user must restart the discovery process using the back button in the wizzard.
The satochip firmware version supported has been updated to v0.9. (v0.9 is a patch that allows message signing for altcoins with a custom format. There is no impact for Bitcoin Cash.). During wallet creation, the electrum client checks the version of the satochip to ensure that it supports the latest features. If not, a warning is displayed to the user.
> Satochip wip

- lib/plugins.py
As per a Telegram chat with @markblundeberg  -- we realized that:
The @hook decorator was registering functions globally for all plugins,
even ones not decorated with @hook would get picked up.
This change fixes it so that only functions decorated with @hook get
picked up.
~~**This commit is not 100% ready for merge to mainline.  I still have to do
some due diligence and verify no extant plugins DEPENDED on the old
behavior for correct operation!**~~
EDIT: It turns out this PR is safe to merge.  I ran through all the code and verified all hook-like-functions are indeed decorated with `@hook`.
> Plugins: Fix to @hook / @run_hook mechanism

- gui/qt/exception_window.py
- gui/qt/main_window.py
This adds:
- Crash reporter can now be disabled/enabled from preferences
- Crash reporter layout has been cleaned up
- Preferences pane layout has been cleaned up to waste less real-estate and the 5 prefs tabs have been collapsed into 4.
This closes #1672 .
Screenshots:
---
> Add crash reporter to prefs, Crash reporter layout fixes, & Prefs Layout fixes

- electron-cash
- lib/commands.py
- lib/daemon.py
- lib/plugins.py
While we can't add new @commands in plugins (since it's too late), we can have the daemon RPC accept arbitrary subcommands and dispatch them to plugins, when desired.
Note in order to get this working on the non-GUI daemon, you have to add a `cmdline.py` to your plugin with a GUI-free implementation of the `class Plugin:`, then put `available_for = ['qt', 'cmdline']` in your plugin's `__init__.py`. In principle also you should do this for `stdio` and `text` which are alternative non-graphical GUIs; each of these can just be short stub files.
I've tested this on a sample plugin and it works well.
~~The usage of metaclass is inspired by this: https://stackoverflow.com/a/3054505/5667904~~
The usage of scan-class-on-init is inspired by  #1669
> allow plugins to register daemon commands using decorator

- lib/plugins.py
We want to avoid `__init__` failing, so just print an error instead.
Error looks like:
```
Ignoring plugin daemon command 'mycmd' from <class 'electroncash_plugins.plugB.qt.Plugin'> (already exists from <class 'electroncash_plugins.plugA.qt.Plugin'>)
```
> tweak daemon command collisions in BasePlugin

- gui/qt/main_window.py
- gui/qt/transaction_dialog.py
- gui/qt/util.py
- lib/commands.py
- lib/wallet.py
Export history how can optionally also download input data to get 100% accurate fees on all tx's. This is specified in the CLI via `--use_net`.  Can also optionally specify a timeout in the CLI for the input fetcher (in case it takes too long) via `--timeout`.
`--show_fiat` has been improved to also show fee value in fiat (along regular satoshis).
Also in this PR:
-  Refactored/enchanced some utility functions from `gui/qt/utils.py` to either be less broken or more useful. 
- GUI Export history has the above options now too (both to download inputs and/or specify a timeout). GUI export history also has a new checkbox "include adddresses" which is useful if you want to know the addresses in a tx in history.
> Improvements to GUI & CLI export history facility + nits

- gui/qt/main_window.py
I assume exported addresses will mostly be used by automated systems like I use. Because of that, having address list in export with no extra whitespace is slightly more parse-friendly.
> nit: remove whitespace from export address list

- android/app/src/main/python/electroncash_gui/android/console.py
Exactly as with fd42160, the Android version needed updated to support
the new Daemon() constructor.
> Android: Address the new required `plugins` parameter added by RP #1670.

- android/app/src/main/java/org/electroncash/electroncash3/Main.kt
This adds a "Delete wallet" button to the wallet-open password prompt, making it possible to delete wallets without first needing to unlock them.  This should help when the wallet password is irretrievably lost for example.  Clicking the button takes you through the normal wallet deletion process with a confirmation dialogue and reminder to save your seed.
> Android (phase 4): Add ability to delete closed wallets

- README.rst
I've tested this but I'm not 100% sure I hit all the steps. Like, does pyenv require gcc to be apt-installed first?
Also I'm not sure what the steps are for Mac. @cculianu can you inform?
> README - add instructions for pyenv

- contrib/requirements/requirements-binaries.txt
The sip module is not needed. We also remove the PyQt5-sip dependency as PyQt5 already has a dependency on the correct version. This makes Python 3.8 usable as PyQt5-sip Python 3.8 wheels are only built for newer versions.
> Remove unused sip dependency for Python 3.8 compatibility 

- plugins/satochip/CardConnector.py
- plugins/satochip/CardDataParser.py
- plugins/satochip/satochip.py
When using passphrase with seed, user sometimes get an error: Recovered authentikey does not correspond to registered authentikey!
See https://github.com/simpleledger/Electron-Cash-SLP/pull/101#issuecomment-561238614
I was able to reproduce the bug with the following setup:
* create a wallet 'w1' using a seed1 stored on Satochip.
* reset seed1 on Satochip and close wallet (and EC)
* when Electron Cash is run again, old wallet w1 opens by default, however this wallet is not valid anymore since it is related to an old seed
* when creating a new wallet w2 from wizard with a new seed2, EC will however check compatibility with w1, thus raising an error.
This PR also improves error messages when pairing Satochip with the wrong wallet file.
> [satochip] Patch "Recovered authentikey does not correspond to registered authentikey" error

- lib/network.py
Long story behind this one, but hopefully informative. Let's start off with an explanation of lowfee messages (for ABC as of today -- see src/validation.cpp AcceptToMemoryPoolWorker)
- If the mempool is congested, the fee floor rises. The mempool congestion
floor is the first feerate check, and produces 'mempool min fee not met'.
We don't normally see this.
- If the fee is below the regular limit (typically 1 sat/byte) then we will
get 'insufficient priority' EXCEPT.....
if the transaction is 'high priority' (burns lots of coin days) then
it will bypass the 1 sat/byte check, and move on to the free limiter.
- If the free limiter rejects a transaction then you get:
'rate limited free transaction'
- By default, the free limiter allows 0 free transactions. In other words
even if your …
> add another lowfee net reject message

- .gitignore
- android/app/src/main/java/org/electroncash/electroncash3/Dialog.kt
- android/app/src/main/java/org/electroncash/electroncash3/Send.kt
- android/app/src/main/java/org/electroncash/electroncash3/Util.kt
- lib/i18n.py
- lib/locale/.gitignore
- lib/locale/__init__.py
- setup.py
@cculianu: The workaround of making the `locale` directory a Python package is no longer needed in the current version of Chaquopy, so I've restored the previous way of finding it. Does that look alright to you?
> Android fixes

- gui/qt/network_dialog.py
When a tor proxy is found that does not match the current proxy setting, we have to make sure the "use tor" checkbox is unchecked and the proxy settings editable.
> Network dialog: Correctly handle finding a different tor proxy

- lib/wallet.py
```
lib/wallet.py:1556: SyntaxWarning: "is" with a literal. Did you mean "=="?
if label is '':
```
> Wallet.py: Fix warning about "is" with a literal

- gui/qt/qrreader/camera_dialog.py
When the Qr scanner has to fall back to using non-ideal resolutions it still sorts them so the lowest possible one is used. This is wrong as with non-ideal resolutions we want the highest one to be used.
> Qr scanner: Fix non-ideal resolutions resulting in lowest possible

- lib/servers.json
The instance is comprised a BU full node (1.7) and an ElectrsCash
electrum server (1.0) and run on pretty beefy machine we setup to
provide a robust instance.
> Add Bitcoin Unlimited managed Electrum server to the white list

- contrib/base.sh
- contrib/build-linux/appimage/Dockerfile_ub1604
In fd3701fd6c64a726fd201e53e77c0cf4e33a5598 we added a new git version to the AppImage build image to support shallow submodule updates.
The problem with this is that it causes a newer glibc to be pulled into the image which breaks older Linux distributions.
As a solution to this we use a git PPA by the Ubuntu Git maintainers that is compiled for Ubuntu 16.04:
https://launchpad.net/~git-core/+archive/ubuntu/ppa?field.series_filter=xenial
Due to a change in git 2.22 shallow clones will fail when using the default git protocol version, so we set protocol.version to version 2 instead. See:
https://public-inbox.org/git/20191013064314.GA28018@sigill.intra.peff.net/
> Build: Fix regression causing newer glibc to be pulled into AppImage

- contrib/build-linux/appimage/Dockerfile_ub1604
- contrib/build-linux/appimage/Dockerfile_ub1804
- contrib/build-linux/appimage/_build.sh
Newer distributions do not install `libxkbcommon-x11` by default anymore and Qt depends on it.
Fixes #1773
> Build: Install libxkbcommon-x11 in AppImage

- lib/tor/controller.py
When the network dialog is open on the proxy tab, the `TorDetector` will run in an interval, which will cause the log to be spammed with messages saying "This port is not an HTTP proxy". Those can be ignored.
> Tor: Ignore noisy "not an HTTP proxy" messages from TorDetector

- contrib/build-wine/electron-cash.nsi
- gui/qt/main_window.py
The text has been made into a format string so years can be updated without additional work from translators in the future.
> About dialog: Update copyright year to 2020 and make localizable

- gui/qt/main_window.py
- lib/wallet.py
- plugins/shuffle/client.py
- plugins/shuffle/coin_utils.py
- plugins/shuffle/qt.py
This is a first pass at trying to decouple the address reservation system from cashshuffle. I've tested it in various ways and it works, but I can't test everything. No rush to merge this, but I'm going to build fusion assuming that something like `wallet.reserve_change_addresses` exists.
For the wallet:
- `make_unsigned_transaction` reserves addresses and keeps using those
until they actually appear in a tx.
- Plugins can also reserve addresses, which blocks them from ever being
used by `make_unsigned_transaction`, or by other plugins.
- The old rule of not filling in old gaps is respected. When we restore
from seed, it's safe to assume those gaps were there for a good reason.
- De-reservation is possible. These aren't just freed from reservation
but rather are actively scheduled to be …
> Add change-address reservation subsystem

- README.rst
The `contrib/make_secp` script makes use of GNU utils including `grealpath`,
these are found in the coreutils package.
> Add coreutils to mac build

- README.rst
While I was following the instructions for running from source on macOS, I needed to install `automake` in addition to `coreutils` in order to compile `secp256k1`. I've updated the README to help others avoid this small hurtle.
> Update requirements for running on macOS

- contrib/requirements/requirements.txt
This was added in 0e6d3499862d1ca51eca3870357a0b89a0940a6b.
The original error was:
```
Cannot load wallet:
Conflict register for file "messages.proto": Address is already defined in file "plugins/shuffle/protobuf/message.proto". Please fix the conflict by adding package name on the proto file, or use different name for the duplication.
```
Our own proto files have since been fixed and Trezor have fixed
their proto files as well:
https://github.com/trezor/trezor-common/commit/279bc1f220d38db9562ac9e22d61c5b94a854f9f#diff-a21d059874674d8247b316b869766a60
I tested this with protobuf-3.11.3 and haven't encountered any errors.
> Requirements: Remove protobuf <3.9 constraint

- lib/keystore.py
- lib/mnemonic.py
Since February, the code reused the normalize routine for mnemonics also
for passphrases.  This had the unintentional side-effect of converting
passphrases to lower-case. This commit fixes it.
Also the accents are no longer stripped from mnemonic words, to conform
to the BIP39 standard.
Incompatibility: If you created a BIP39 wallet with a passphrase that is
not lower-case it would instead have created the wallet for the lower-case
passphrase.  So if your passphrase doesn't work after updating, you may
try it with the lower-case passphrase again.
> BUGFIX bip39 passphrases are not lowercase

- contrib/make_zbar
When improving the build scripts to add Tor support (eda015908e9d6ea9a0adfbda9db55b929c0926ba) we forgot to transfer some Windows specific flags into the new ZBar build scripts, which resulted in the binary depending on additional .dll files that were not bundled into the installer, causing the QR scanner not to work for most users. This patch restores the flags.
> ZBar: Fix Windows build DLL imports

- gui/qt/network_dialog.py
- lib/util.py
- lib/utils/event.py
The `Event` class currently forces every method call to happen on the main thread. There are some use cases where this is not a good idea, so this should be removed. Instead we add the function decorator `@in_main_thread` that invokes the decorated function in the main thread. Every event handler that touches GUI objects or needs to run in the main thread for some other reason needs to be decorated.
> Event: Replace forced main thread invocation with function decorator

- lib/tests/test_interface.py
In 4.1.0 we added support for wildcard certificates which caused the tests to fail. The test was passing data in a format `ssl.match_hostname` did not expect, so the test had to be fixed.
This also adds tests for wildcard certificates and tests the second level sub domains of wildcard certificates fail the test.
closes #1923
> Tests: Fix failing host name test and add wildcard tests

- .travis.yml
- contrib/requirements/requirements-travis.txt
- tox.ini
* Fixed the `.travis.yml` warnings
* We need Bionic as otherwise Qt errors
* Use `coveralls` instead of `python-coveralls` package as the latter is broken
* Add Python 3.7 and 3.8 to the tox configuration
> Travis: Make it work again for Python 3.6, 3.7 and 3.8

- contrib/requirements/requirements.txt
- lib/dnssec.py
- lib/interface.py
- lib/tests/__init__.py
- lib/tests/test_dnssec.py
`dnspython>=2` breaks our dnssec support because we depend on private functions that aren't in 2.0 anymore
> dnssec: fix compat with dnspython 1.16 and 2.0.0

- lib/tests/test_cashaddrenc.py
sometimes the code would just manipulate the prefix of the address causing the decode function not to raise an exception.
> tests: fix cashaddr checksum test unreliability

- contrib/build-linux/appimage/_build.sh
- contrib/build-wine/_build.sh
- contrib/osx/make_osx
- ios/make_ios_project.sh
If there is a collision between a branch name and a commit hash, git will choose the branch, even if the full 40-hex-long commit hash is given. GitHub disallows branches/tags with such a name but git itself does not. By adding the `^{commit}` syntax sugar after a ref name, we can tell git that we want the commit hash to be preferred, and hence we don't need to trust GitHub (only git).
see https://security.stackexchange.com/questions/225411/
from https://github.com/spesmilo/electrum/commit/f5f3394552c4efa46b71e13d1ad3ab171936bd88 adjusted for our repo. Also includes a fix for `make_ios_project.sh` checking out a branch.
> git sanity: enforce "git checkout commithash" actually pulls commit

- gui/qt/network_dialog.py
- lib/tor/controller.py
- plugins/fusion/qt.py
The messages now refer either an integrated Tor, a system Tor or just Tor. When no Tor binary is detected, Tor will be deactivated
and there will be a message about this in the tooltip of the settings.
This also changes the Fusion "Click here to resolve" to "Click this popup to resolve" because "here" does not make it clear whether to click on the popup or on the Fusion button it is pointing to.
closes #1932
> Tor: Make the messages refer to a specific Tor binary

- plugins/fusion/conf.py
- plugins/fusion/plugin.py
(This is an SSL proxy on same host, going to same nonSSL server)
Also, migrate over existing users who are on previous non-SSL server
and have for some reason gotten it hard-saved in their config.
> [fusion] update default server to use SSL

- lib/asert_daa.py
- lib/blockchain.py
- lib/networks.py
Summary
---
- Default activation is for MTP >= 1605441600, which is taken from BCHN sources chainparams.cpp and corresponds to the Nov. 15th 2020 12:00:00 UTC upgrade time.
- Can override activation time for testing via the `ASERT_MTP=` environment variable
Test Plan
---
You can test this now by hitting one of the ASERT testnet servers.  Either mine or imaginary username's server. 
1. Start `electron-cash` in testnet mode, specifying the hard fork MTP we set up:
**`$ ASERT_MTP=1597096200 ./electron-cash -v --testnet`**
2. Hit either my server or im_uname's server: 
- `blackie.c3-soft.com` port `61002`
- `testnet.imaginary.cash` port `50002`
You should notice that there is a fork and your client should reject the other chain in the console output (cannot connect header, bad chunk …
> Add support for the ASERTi3-2d DAA for the Nov. 15th, 2020 Upgrade

- setup.py
This pull request makes PyQt5 not install-able by default by setup.py, which allows more control for users what to install, as some users don't use GUI interface and use daemon or some CLI integrations instead, where pyqt5 is an extra 60-120 MB and also it makes it impossible to install it without some additional packages on light linuxes(especially when building slim docker images), like alpine linux.
PyQt5 can now be installed by running `pip install .[gui]` or `pip install .[full]`
It might needed to be documented in README and discussed further.
I have checked all the binary builds, all the builds install PyQt5 by using `contrib/requirements/requirements-binaries.txt`, so the setup.py install_requires of pyqt5 is not neccesary.
The only build which doesn't do so is …
> Made PyQt5 optional by default and installable by [full] or [gui] extra requires

- contrib/make_locale
I'm trying to build android app on Windows , but errors with make_locale becomes a show stopper.
Between line 24 and line 31 make_locale create a shell to execute a 'find' command to search all the files that needs to be translated.  Although there is indeed a 'find' command on Windows, but it's totally different from the unix-like one. 
This PR fix the problem by rewriting the relevant parts with pure os-agnostic python code.
> Fix make_locale to be more pythonic

- android/app/src/main/java/org/electroncash/electroncash3/Send.kt
We might just as well do it with since there isn't really any downside
and it makes the wallet Look Cool[tm].
> android: Sign transaction with schnorr

- gui/qt/history_list.py
- plugins/fusion/qt.py
- plugins/shuffle_deprecated/qt.py
This way an edited label can be filtered directly instead of during
update of the entire history_list.
This can be seen if someone has CashFusion running and the "Hide
CashFusions" option enabled and proceeds to rename a label to start with
"CashFusion ".
Without this fix the transaction is not hidden until the
wallet is restarted or the "Hide CashFusions" option is toggled off and
on.
> Run history_list_filter hook on updated labels

- lib/servers_testnet4.json
electroncash.de is running testnet4 - feel free to test on:
electroncash.de:54003 tcp
electroncash.de:54004 ssl
jktsologn7uprtwn7gsgmwuddj6rxsqmwc2vaug7jwcwzm2bxqnfpwad.onion:54003 tcp onion
electroncash.de:64003 websocket tcp
electroncash.de:64004 websocket ssl
> Add electroncash.de testnet4 server

- lib/commands.py
- lib/wallet.py
This PR is a backport of https://github.com/spesmilo/electrum/pull/6532
It makes it possible to use payto/paytomany+broadcast commands in concurrent environments when turning addtransaction flag on by adding tx to local history before a full network round-trip.
> Added addtransaction arg to payto/paytomany

- plugins/ledger/ledger.py
Starting in version 1.4.0 of the Ledger Bitcoin app, additional data needs to be sent for inputs to prevent the firmware warning about unverified inputs. See https://donjon.ledger.com/lsb/010/
> Ledger: Fix warning about unverified inputs

- plugins/ledger/ledger.py
The last change broke Ledger Nano S/X on firmware versions < 1.4.0.
We now check the firmware version to see if we need to use trusted inputs or not. The behaviour with firmware version < 1.4.0 is the same as before.
> Ledger: Test firmware version for trusted input requirement

- contrib/deterministic-build/requirements-hw.txt
Required to use the new firmware.
> Ledger: Update btchip-python version for deterministic build

- lib/tests/test_paymentrequests.py
Some basic tests for BIP-70 processing.
This is basically some happy-testing and more should be done to cover
error scenarios and signature verification.
> Add paymentrequest tests

- .gitignore
- tox.ini
Generate a HTML report for coverage when running tox.
Also add the report .gitignore
> Enable coverage HTML report

- lib/commands.py
- lib/keystore.py
- lib/rpa_paycode.py
- lib/rpaaddr.py
- lib/schnorr.py
- lib/transaction.py
- lib/wallet.py
This implements RPA Re-usable payment address (AKA Paycodes) with a CLI.
Note this only implements the basic functions of generating a paycode, a transaction, and extracting private key. Other functions such as storing the key in the keystore will be implemented in the next stages.
This is a continuation of https://github.com/Electron-Cash/Electron-Cash/pull/2001.  It was redone on a new branch to avoid cherry picked commits from master.
It incorporates feedback from @cculianu including:
* Avoiding changing cashaddr module and instead use a new rpaaddr module.
* Avoiding changing default behavior in libsecp256k1 by passing null value rather than empty byte string for ndata
* Pythonic looping syntax
* spaces after commas in code
* Avoiding literal "0" for cashaddr and instead use …
> RPA Paycodes

- electroncash_gui/qt/main_window.py
- electroncash_gui/qt/paytoedit.py
Summary
---
Due to the announcement by cointext that they will be ceasing operations
as of Nov. 14th, 2020, we need to disable this facility from Electron
Cash.  See announcement:
https://cointext.io/en/nov14/?utm_source=CoinText&utm_campaign=53b0c5ed7d-EMAIL_CAMPAIGN_2020_10_19_02_15
All code that was added for PR #1407 (and subsequent clean-up commits) has
been revered by this commit.  It's as if cointext: was never in the
codebase at all.
Test Plan
---
1. Start the Qt app
2. Use the send tab, paste a paymentrequest URL e.g. bitcoincash: (or bchtest:) <-- should still work
3. Make sure sending to cashaccont: and simple addresses still works.
4. Make sure cointext:1234567 no longer works.
> Disable `cointext:` support from send tab & remove cointext code

- electroncash_plugins/fusion/server.py
If we use a pure-python schnorr verifier, we will be way too slow to
verify the hundreds of signatures that fly at us during covert
submissions. (Each verify does two elliptic curve multiplies!
Every covert component has one verification for the blind sig,
and every input additionally has one verification for the tx
sig. So easily a few hundred schnorr verifies.)
> [fusion] require fast schnorr for server

- electroncash_plugins/fusion/fusion.py
- electroncash_plugins/fusion/plugin.py
- electroncash_plugins/fusion/qt.py
This is a package of a variety of related tweaks. See individual commits for each separate idea.
Primarily this is to fix a known issue that is likely causing #2010 : we should not be starting autofusions when network is down or wallet is not up to date. To make this even stronger, we will stop existing waiting autofusions if the network is down for an extended time.
Some related / needed changes as well:
- Misc refactorings.
- Also stop manual fusions when switching servers.
- Race fix.
- Better handling on 'confirmed-only' case.
> [Fusion] Various fixes to starting and stopping behaviour

- electroncash_plugins/fusion/fusion.py
- electroncash_plugins/fusion/server.py
- electroncash_plugins/fusion/validation.py
- catch timeouts when trying to broadcast (TimeoutException is not subclass of ServerError)
- add some error catching around check_input_electrumx()
- less noisy logs during blame
> [fusion] better handling on interactions with electrumx server

- electroncash/tor/controller.py
This prevents Ctrl-C from hitting the tor child process.
Note that since Tor gets started with `__OwningControllerProcess <electron_cash_pid>`,
it will always die even if we kill -9 the parent.
> daemonize Tor subprocess

- electroncash/servers.json
They run ABC 0.22 servers which may cause problems post-upgrade. Tried to contact them through op_return on their donation address but didn't get any reply or action.
> Remove greedyhog server

- electroncash/servers.json
This reverts commit 0d08c9d0ecdd764c599f750ba91e13842261aff0.
The server has switched back to the BCH chain.
> Revert "Remove greedyhog server"

- electroncash_plugins/ledger/ledger.py
Ledger announced changes to the USB ids here:
https://www.ledger.com/windows-10-update-sunsetting-u2f-tunnel-transport-for-ledger-devices/
This patch adds the new USB ids.
closes #2054
> Ledger: Update USB ids for app-bitcoin version >= 1.5.1

- electroncash_plugins/fusion/plugin.py
We were sometimes getting `AttributeError: 'Fusion' object has no attribute 'inputs'`
here, which happens when the Fusion object runs its cleanup.
> [fusion] fix minor race leading to exception

- electroncash_plugins/trezor/clientbase.py
Backport https://github.com/spesmilo/electrum/pull/6471 from Electrum, that fixes [Trezor with autolock error](https://github.com/spesmilo/electrum/issues/6457).
I cannot test this because I don't have a Trezor.
> trezor: use `init_device` instead of `ping` to check connection

- electron-cash
run_non_RPC has too many branches, making it hard to follow.  The
refactoring extracts two new functions: create_wallet and
restore_wallet.  I also did some minor changes in style to fix pylint
errors, like keeping lines under 80 characters.
See too-many-branches (R0912) on
https://pylint.readthedocs.io/en/latest/technical_reference/features.html?highlight=r0912#design-checker-messages
> Refactor run_non_RPC

- contrib/requirements/requirements.txt
- electroncash_plugins/fusion/compatibility.py
- electroncash_plugins/fusion/fusion.py
- electroncash_plugins/fusion/server.py
Ubuntu 20.04 ships python3-protobuf 3.6.1 which, when running from source, causes fusions to fail with mysterious errors like "decode error".
Also, one of our requirements.txt was not being strict enough.
> [fusion] better detect protobuf incompatibility

- electroncash/storage.py
The vast majority of the time taken by `save_transactions(write=True)` is in `json.dumps`.
```
>>> s.print_stats()
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.004    0.004    3.905    3.905 electroncash/wallet.py:416(save_transactions)
17    0.002    0.000    3.746    0.220 stdlib/json/__init__.py:183(dumps)
17    0.300    0.018    3.744    0.220 stdlib/json/encoder.py:182(encode)
8886    0.582    0.000    3.439    0.000 stdlib/json/encoder.py:413(_iterencode)
18271/8884    1.381    0.000    2.855    0.000 stdlib/json/encoder.py:333(_iterencode_dict)
1    0.000    0.000    2.234    2.234 electroncash/storage.py:176(write)
1    0.001    0.001    2.234    2.234 electroncash/storage.py:183(_write)
8    0.001    0.000    1.596    0.200 …
```
> Remove expensive json.dumps calls in storage.put

- electroncash/storage.py
The standard json module has an optimized C encoder, but that doesn't currently support indentation. So if you request indentation, it falls back on the slower Python encoder.
Readability doesn't matter for encrypted wallets, so I've disabled indentation when the wallet is encrypted. This speeds up `storage.write` by about 30%.
> Use faster JSON encoder settings when wallet is encrypted

- electroncash/wallet.py
Currently `save_addresses` is called after every address is added. Since this copies the entire address list to storage every time, the cost is n**2 in the number of addresses. For wallets with thousands of addresses, the initial synchronization process was spending more than half of its time in `save_addresses`.
So I've changed it to save the addresses in the same situations as it saves the transactions:
* When synchronization is complete.
* When the wallet is closed.
This reduced the synchronization time of an 11,000-address wallet from 20 minutes to 6.
> Fix redundant calls to save_addresses during synchronization

- electroncash/network.py
- electroncash/tor/__init__.py
- electroncash/tor/controller.py
Stem release 1.8.0 moved to using `asyncio`, breaking our method of preventing the Tor control connection going through Tor itself.
To fix this we introduce a new general proxy bypass mechanism that checks the list `network.bypass_proxy_filters`, calling each function in it. If any of the functions returns true, a normal socket instead of a proxied socket will be returned.
The Tor controller provides such a filter that is installed by default and returns True when called from `stem.socket.ControlPort`.
> Tor: Fix proxy bypass for stem version 1.8.0

- electron-cash
While backporting #2095 for Electrum ABC, I noticed a probable typo. The function `run_cmdline` does not use the argument `result`, and AFAIK it is undefined when it is passed to the function.
> remove a superfluous parameter in function run_cmdline

- electroncash_plugins/satochip/qt.py
- electroncash_plugins/satochip/satochip.py
This pull request brings some improvements to the Satochip plugin based on users feedback:
Seed generation: use BIP39 by default for better compatibility (instead of electrum seeds):
* Most (all?) hardware wallets use BIP39 seeds in combination with BIP43-style derivation paths (like m / purpose' / coin_type' / account' / change / address_index)
* Electron-Cash/Electrum use BIP43 derivation paths for hardware wallets AND for BIP39 seeds imported in software wallets.
* Electrum seeds (not BIP39) use seed versioning instead of purpose derivation path.
* Software wallets with Electrum seeds use "m / change / address_index" derivation paths (so not BIP43).
So for better interoperability, we switch to BIP39 by default. User can still import an electrum seed if needed.
User interface …
> Satochip plugin improvements 

- contrib/build-linux/appimage/Dockerfile_ub1604
- contrib/build-wine/docker/Dockerfile
See https://github.com/mchehab/zbar/issues/132
This needs `autopoint` to be installed.
> Zbar: Update to git master to fix build with autoconf 2.70

- electroncash/address.py
- electroncash_gui/qt/main_window.py
Legacy addresses are the source of confusion for many BCH users.
See [Why you should never send your BCH to BTC address](https://blog.cex.io/news/why-you-should-never-send-bch-to-btc-address-21346).
This changeset creates a popup warning window when the user tries to
send BCH to a legacy address.  The window has a "Never show this again"
checkbox.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/electron-cash/electron-cash/2129)
> Warn if a legacy addres is used

- contrib/build-wine/_build.sh
This version includes the fix for icon issue causing not reproducible builds, so this removes the note about that.
> NSIS: Update to version 3.06.1

- contrib/base.sh
- contrib/build-linux/appimage/Dockerfile_ub1804
- contrib/build-linux/appimage/build.sh
- contrib/build-wine/build.sh
- contrib/build-wine/docker/Dockerfile
The default Ubuntu mirror (archive.ubuntu.com) is slow depending on the location of the builder. This allows to override the Ubuntu mirror URL by setting the `UBUNTU_MIRROR` environment variable.
> Build: Allow to override Ubuntu mirror URL

- contrib/requirements/requirements-binaries.txt
- contrib/requirements/requirements.txt
`dnspython` with DNSSEC pulls in `cryptography` so it should not be in `requirements.txt`.
> Requirements: Move cryptography dependency into binary requirements

- .travis.yml
- tox.ini
The tests were broken by #2156 because they do not pull in the `cryptography` package anymore:
https://travis-ci.org/github/Electron-Cash/Electron-Cash/jobs/757923867
This adds the dependency and also adds a Travis build for Python 3.9.
> Tests: Fix missing dnspython dependency causing DNSSEC tests to fail

- contrib/build-wine/_build.sh
- contrib/build-wine/requirements-wine-build.txt
- contrib/requirements/requirements-wine-build.txt
PyInstaller 3.6 fixed the MinGW build issue we used a patch for:
https://github.com/pyinstaller/pyinstaller/commit/6df55e45876968537585c197f2b86f67d0242305
but version 4.2 broke the MinGW build again:
https://github.com/pyinstaller/pyinstaller/commit/99db9ab98d63b028724d38f241424d21df44afcf
this fails with `windres: no resources` because the preprocessed RC file is essentially empty. Windows RC seems to ignore this. To fix it we add a patch that just removes the RC file build:
https://github.com/EchterAgo/pyinstaller/commit/d6f3d02365ba68ffc84169c56c292701f346110e
> Windows: Use PyInstaller version 4.2

- contrib/base.sh
- contrib/build-linux/appimage/_build.sh
- contrib/build-wine/_build.sh
- contrib/make_linux_sdist
- contrib/osx/make_osx
This filters out the `android-*` and `ios_*` tags by default but can also be used to select specific tag prefixes.
> Build: Add git_describe_filtered helper

- contrib/build-linux/appimage/_build.sh
On Ubuntu host, build succeeded; but e.g. on Manjaro host, it failed with:
```
./build.sh: line 233: /opt/electrum/contrib/build-linux/appimage/../../../contrib/build-linux/appimage/.cache/appimage/appimagetool: No such file or directory
```
This seems to be caused by applications like `AppImageLauncher` registering the AppImage magic bytes with `binfmt_misc` leaking into the Docker container.
See also: https://github.com/AppImage/pkg2appimage/issues/373
> appimage build: build was failing on some host systems

- contrib/build-wine/electron-cash.nsi
When there is an existing installation and the user chose to uninstall, wait for the uninstaller to finish. Normal `ExecWait` doesn't work because by default the uninstaller spawns a new process. This also exits the installation if the uninstall fails.
> NSIS: Wait for the uninstaller to finish

- contrib/build-wine/electron-cash.nsi
Installing when the process is running can have unintended effects:
See https://github.com/spesmilo/electrum/issues/6748
To address this we disallow (un)installing as long as the process is running. To detect that the process is we try to open the .exe file with write access (append, so we don't truncate the file) and if that fails we know the process is running.
> NSIS: Ensure the process is not running when (un)installing

- contrib/build-linux/appimage/Dockerfile_ub1804
- contrib/build-wine/docker/Dockerfile
https://nvd.nist.gov/vuln/detail/CVE-2021-21300
https://launchpad.net/ubuntu/+source/git/1:2.17.1-1ubuntu0.8
> Build: Use git version with patch for CVE-2021-21300

- contrib/build-linux/appimage/Dockerfile_ub1804
- contrib/build-linux/appimage/_build.sh
Ubuntu 20.04 needs `libxcb-xinerama.so.0` and Debian 10 needs `libxcb-util.so.1` for the Qt `xcb` plugin.
See #2189
Closes #2196
> AppImage: Include libxcb into the image

- electroncash/base_wizard.py
- electroncash_gui/qt/installwizard.py
This allows a user to scan a set of known derivation paths for
transactions when restoring a wallet from a seed.
> Install Wizard: Add derivation path scanner

- electroncash/base_wizard.py
HW wallets have no seed available but is still considered 'standard'.
Closes #2207
> Skip path derivation scan if seed is unavailable

- electroncash/servers.json
- electroncash/servers_testnet.json
electrs.electroncash.de is running stable for a while now and can be added to the default list
> Add electrs.electroncash.de

- contrib/base.sh
This has an important fix:
* bpo-43631: high-severity CVE-2021-3449 and CVE-2021-3450 were published for OpenSSL, it's been upgraded to 1.1.1k in CI, and macOS and Windows installers.
AFAICT we are not affected by CVE-2021-3450, but the Fusion/Shuffle server is affected by CVE-2021-3449.
> Python: Update to version 3.8.9

- electroncash/rsakey.py
This line was introduced in the original implementation of the function
back in 2015, and never cleaned up: e8d30129eae10b5efeaa9e95a900576e41dd2bf1
Related issue: https://github.com/Electron-Cash/Electron-Cash/issues/2213
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/electron-cash/electron-cash/2224)
> Removed unreachable line of code

- contrib/build-linux/appimage/Dockerfile_ub1804
This has some important fixes:
* SECURITY UPDATE: NULL pointer deref in signature_algorithms processing
- debian/patches/CVE-2021-3449-1.patch: fix NULL pointer dereference in
ssl/statem/extensions.c.
- debian/patches/CVE-2021-3449-2.patch: teach TLSProxy how to encrypt
<= TLSv1.2 ETM records in util/perl/TLSProxy/Message.pm.
- debian/patches/CVE-2021-3449-3.patch: add a test to
test/recipes/70-test_renegotiation.t.
- debian/patches/CVE-2021-3449-4.patch: ensure buffer/length pairs are
always in sync in ssl/s3_lib.c, ssl/ssl_lib.c,
ssl/statem/extensions.c, ssl/statem/extensions_clnt.c,
ssl/statem/statem_clnt.c, ssl/statem/statem_srvr.c.
- CVE-2021-3449
This also updates libudev-dev to version 237-3ubuntu10.45, the old version is not available anymore.
I tested the AppImage. …
> AppImage: Update OpenSSL to version 1.1.1-1ubuntu2.1~18.04.9

- contrib/build-wine/_build.sh
Before this change, whoever has a copy of the Python release signing key is a trusted third party. This commit changes this so that in addition to checking the signature of the installers, the checksums are also verified.
This is motivated by the Python 3.8.9 release (2021-04-02) being replaced with a different version (2021-04-06) that didn't match the PGP signature.
> Build: Verify the Python checksums

- contrib/make_locale
Previously it just continued running even if the commands failed, which would lead to confusing errors later in the build process.
I've tested both success and failure on both Windows and Linux.
> Make make_locale check exit status of gettext commands

- electroncash/plugins.py
It was previously only looking at {user_dir}/external_plugins and
creating that directory.
Fixes #2300
> Look for external plugins in ELECTRON_CASH_PATH

- electroncash/daemon.py
This pull request allows to disable JSON-RPC server (and therefore it's file lock) setup.
It is useful in cases of using Daemon for only some of it's functionality (properly starting network, fx thread, handling wallets), and using custom JSON-RPC solution (i.e. BitcartCC) instead of default server. This allows starting both custom daemon object and electron cash gui at the same time. As the param is appended with a default value, no behaviour should be changed by default.
> Support disabling JSON-RPC server in Daemon

- electroncash_plugins/fusion/fusion.py
Since the server is now going up to 8 BCH tier level, it makes sense to start paying closer attention to this.
> WIP: [fusion] Increase 'fuzz fee' to be tier/10^6

- electroncash/commands.py
- electroncash/simple_config.py
- electroncash/wallet.py
This pull request adds `feerate` parameter to CLI functions `payto` and `paytomany`. It allows setting feerate for a transaction without for example calling payto once, getting tx size (via a function that is not exposed by default commands.py) and then calling payto once again with calculated fee.
> Add feerate argument to payto/paytomany

- ios/CustomCode/ViewsForIB.h
- ios/ElectronCash/electroncash_gui/ios_native/gui.py
- ios/ElectronCash/electroncash_gui/ios_native/send.py
- ios/Resources/Send.xib
This pull request concerns the iOS version only. The aim is to bring op_return support to the mobile wallet [#1378]. The desktop version already has op_return support.
I open it as a WIP for discussion and feedback.
The goals are the following:
If anything is missing please let me know.
> [iOS] Support OP_RETURN tansaction outputs

- electroncash/daemon.py
This pull request finalizes PR #2305 and fixes some issues related to using it. Sorry, before I introduced it as a way to avoid creating file lock, got to proper shutdown only now (: If actually starting the daemon thread with listen_jsonrpc=False (required for proper shutdown later), it would show `AttributeError: server is not defined` because `init_server` wasn't called, so creating it a bit earlier. Another fix is to not cleanup lockfile if listen_jsonrpc is False, because it is unused anyway (see spesmilo/electrum#7396)
> Fix daemon running in non-jsonrpc mode

- electroncash_gui/qt/main_window.py
- electroncash_plugins/fusion/conf.py
- electroncash_plugins/fusion/plugin.py
- electroncash_plugins/fusion/qt.py
- electroncash_plugins/fusion/util.py
**Merge instructions**: Please squash
---
We add a new checkbox to the send tab, "Spend only fused coins", which
only appears if CashFusion is loaded and if the wallet in question can
fuse.
If checked, we do something similar to the CashShuffle plugin -- we
refuse to spend coins that aren't yet fused. We also try to "force-add"
coins that live on the same address as fused coins, regardless of fused
status.
The checkbox's state is per-wallet and is persisted across restarts.
The determination of whether a coin is a fusion coin uses some
heuristics -- it looks for whether the special "cashfusion" lokad id 
is present in the txn, and also if at least 1 input is signed by us.
If the user gets a "not enough funds" error in the send tab, additional
text will be printed at the bottom if there …
> Add "spend only fused coins" to Send tab

- electroncash/contacts.py
The OpenAlias regex rejected the address containing bitcoincash: prefix. I think it should be accepted both with and without the cashaddr prefix.
> Make OpenAlias accept 'bitcoincash:' prefix

- electroncash_plugins/fusion/conf.py
- electroncash_plugins/fusion/plugin.py
- electroncash_plugins/fusion/qt.py
Introduce the notion of 'depth' in fusion transactions.
The user can set a preferred depth that will cause further fusions to
halt once a threshold of all sats (currently hardcoded to 95%) has this
depth.
Only spend coins that satisfies this depth.
By default the depth is set to 0 which means that the fusing will
continue forever (same as current behaviour).
> fusion: Add depth checks

- electroncash/web.py
It seems like bitcoin.com scrapped that service *sigh*
They are redirecting to blockchair for mainnet, but lack testnet3
support.
Use blockchain.com as the default explorer for testnet3.
> Remove bitcoin.com block explorer

- electroncash_plugins/fusion/qt.py
Put the green icon in the status when a coin shares an address with a
fully fused coin. Also clarify via tooltip.
> fusion: Clarify status of coins on fused address

- electroncash/address.py
This adds the native introspection opcodes for the up-coming May 2022 consensus upgrade. 
- Spec: https://gitlab.com/GeneralProtocols/research/chips/-/blob/master/CHIP-2021-02-Add-Native-Introspection-Opcodes.md
- Implementation in BCHN: https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node/-/merge_requests/1208
> Add native introspection opcodes (upcoming May 2022 additions to script)

- electroncash/commands.py
- electroncash/simple_config.py
This is useful to not store some confidential info like opened wallets. It is also useful if an app needs to set some variables for it's running time but doesn't need to interfere with gui
Also see spesmilo/electrum#5898
> Add ability to forget config on exit

- electroncash/commands.py
- electroncash/paymentrequest.py
- electroncash/wallet.py
- electroncash_gui/qt/util.py
- ios/ElectronCash/electroncash_gui/ios_native/receive.py
This pull request implements unconfirmed status for invoices. If invoice is unconfirmed it indeed can't be fully considered paid (though as far as I know double-spends are very rare on bch). Also it fixes confirmations calculation bug (classic off-by-one (: )
Marking this PR as draft because it needs some review comments before I can proceed. 
Applied similar fix to spesmilo/electrum@d94d443082a6f71b651625e13318ad6b05b11318
This PR is similar to spesmilo/electrum@90abfda12bf78ce13332ab0474dcade418a211b1
The main question so far is: are you ok with making unconfirmed status number code equal to 7 and not 4 to match electrum's (they also have some lightning statuses which aren't needed here). If not, what about changing getrequest output format everywhere to provide two fields like electrum …
> Implement unconfirmed invoices status

- electroncash/servers.json
The electrum.bitcoinverde.org electrum server is written, hosted, and maintained by the Bitcoin Verde team.  The server is open source, written from scratch, and is bundled with the Bitcoin Verde node.
It is a new server implementation and may have bugs, but it has been tested against the current version of Electron Cash (v4.2.5) and I have not experienced any issues.  If any incompatibilities are found, please respond and I'll fix them.
> Added electrum.bitcoinverde.org to server list.

- electroncash_plugins/fusion/qt.py
1. I confirmed that all `setValue` calls have correct typing after this fix.
2. I assume that the original behavior would have used implicit `int()` truncation, but given the usage and scale (large number) of the value `sel_count`, I chose to use `round()` as the conversion.
There may be other values in fusion requiring updates. I didn't immediately see any. Leaving the PR open to edits from maintainers.
Intended as starting point for solution to #2393
> Update(s) to cashfusion qt for py310 removal of coercion 

- electroncash_plugins/fusion/plugin.py
A better solution is probably to just have a certain number of dusts that we protect against, but for now, this is just a number change that requires no logic change.
This is the proposal implemented:
| Wallet Total Value | Required to Start Fusion @95%           | Note                   | Required to Start Fusion @99.9%      | Note                |
|--------------------|-----------------------------------------|------------------------|--------------------------------------|---------------------|
| 100 BCH ($50,000)  | 5.00000 BCH ($2500.000) (915,751 dusts) | Too high before fusion | 0.10000 BCH ($50.000) (18,315 dusts) | Fine                |
| 10 BCH ($5,000)    | 0.50000 BCH ($250.000) (91,575 dusts)   | Too high before fusion | 0.01000 BCH ($5.000) (1,832 dusts)   | Fine …
> easy fix to allow fusions to continue while keeping dust protection

- electroncash/network.py
- electroncash/synchronizer.py
- electroncash/wallet.py
- electroncash_gui/qt/address_list.py
- electroncash_gui/qt/main_window.py
Closes #2026
This new option allows the wallet to auto-retire "old" change addresses.  This should drastically improve startup times for large cashfusoin wallets and should also make it so that large cash fusion wallets can operate indefinitely.  Right now there is a server-side limit in Fulcrum and ElectrumX on the number of subscriptions a client may have (about 50k to 75k depending on server version). With very large/old cashfusion wallets, this limit may be reached currently.
With this PR, the limit shouldn't normally be reached.  See: #2026 for discussion.
An "old" change address is retired if:
- its index is < 1000 from the latest change address (this magic number of 1000 is GUI configurable)
- It has a trivial history of 2 txs: 1 in, 1 out
- It has 0 balance.
All other change …
> Add new option: "Retire unused change addresses" 

- contrib/build-wine/_build.sh
When pip needs to generate an executable for a Python script entry point it does so using `ZipFile.writestr(filename, data)`. This produces a non-deterministic timestamp in the resulting zip. If we use `ZipInfo` with just a filename instead the constructor sets the default timestamp of `1980-01-01 00:00:00`.
> Build: Patch pip vendored distlib to produce deterministic zip archives

- contrib/build-wine/docker/Dockerfile
- contrib/build-wine/docker/wrapper.cpp
- contrib/build-wine/docker/wrapper_install.bat
By default, the MSVC linker includes a timestamp in the PE header which makes the build not reproducible. There is a `/Brepro` flag that makes the timestamps deterministic.
Unfortunately setuptools provides no way to pass arguments to the MSVC linker and there is no way to change the behavior using environment variables. The `CL` environment variable also can not be used to pass flags to the linker because setuptools calls the linker directly.
To fix this we compile and install a wrapper executable that adjusts the arguments passed to the real linker binary to always include the `/Brepro` flag.
Co-authored-by: Calin Culianu <calin.culianu@gmail.com>
> Build: Install a MSVC linker wrapper to make PE timestamps deterministic

- electroncash/wallet.py
- electroncash_gui/qt/history_list.py
- electroncash_gui/qt/main_window.py
This option is default-on.  This implementation is an alternative to
PR #2431.  It is a second attempt to "undo the damage" of CTOR on the
wallet UI and avoid temporary negative intermediate balances.
The approach taken here is to always sort txns in the same block by
receives-first.  Thus all txns for the same block that have a net
positive effect on wallet balance will appear before these txns in the
same block with a net negative effect on wallet balance.  This is a
quick and performant way to avoid intermediate negative wallet balances
in the history tab (due to CTOR).
---
Special thanks to matricz, molecular, Jonas, and @imaginaryusername for helping to brainstorm this one.
> CTOR workaround approach 2: Always display receives before sends (for the same block)

- contrib/make_tor
This upgrades Tor from version 0.4.5.7 to version 0.4.7.7.
This also disables the relay module which is not needed for our use.
Release notes:
* https://blog.torproject.org/new-release-tor-0458/
* https://blog.torproject.org/new-stable-security-releases-03515-0449-0459-0465/
* https://blog.torproject.org/new-stable-releases-tor-03516-04510-and-0467/
* https://forum.torproject.net/t/release-0-3-5-17-0-4-5-11-0-4-6-8-and-0-4-7-2-alpha/148
* https://forum.torproject.net/t/release-0-4-5-12-and-0-4-6-10/2024
* https://forum.torproject.net/t/stable-release-0-4-7-7/3108/2
This includes important security updates:
Version 0.4.6.5:
* Major bugfixes (security):
* Don't allow relays to spoof RELAY_END or RELAY_RESOLVED cell on half-closed streams. Previously, clients failed to validate which hop …
> Tor: Update to version 0.4.7.7 with a patch for static linking

- contrib/build-wine/docker/Dockerfile
Wine version 7.6 improves the reliability of installing and using the .NET framework, but was unusable for us because of issues with terminal redirection. Wine version 7.7 fixed that issue, so we upgrade to that.
This also adds a wait for wineserver shutdown after installing the linker wrapper as well as a `ngen executequeueditems` after installing MSVC, which is currently disabled because of failures, but which should be there to improve performance.
> Wine: Update to version 7.7

- contrib/build-wine/docker/wrapper.cpp
- contrib/build-wine/docker/wrapper_install.bat
This passes the undocumented `/emittoolversioninfo:no` to stop the linker from adding the "Rich" header which contains tool versions into the file. It also adds the also undocumented `/emitpogophaseinfo` to stop debug info from ending up in the file. Both of these seem to cause non-reproducible builds.
This also installs another wrapper for `cl.exe` which uses the post arguments of the wrapper to pass these flags to the linker.
This also improves the wrapper installer and adds support for post arguments to the wrapper.
> Wine: Pass additional flags to reduce junk in the binaries

- electroncash/address.py
fixes the error in case newer hashlib does not have ripemd and wallet needs it
> use fallback pure python implementation of ripemd160 in address.py

- electroncash/tor/controller.py
The patch for `launch_tor` was incorrectly setting `close_output` as a keyword argument even when the parameter was passed as a positional argument.
> Tor: Fix launch_tor override of close_output argument

- electroncash_plugins/fusion/conf.py
- per https://t.me/cashfusion/13483
Should there also be some update to https://github.com/Electron-Cash/Electron-Cash/blob/e6b891a70f55e22e64f172157b137fb433736123/electroncash_plugins/fusion/plugin.py#L310 ?
> update default cashfusion server to fusion.servo.cash

- contrib/build-linux/appimage/Dockerfile_ub1804
This replaces outdated package versions and adds `cargo` to the package list which is needed to build `cryptography` with the new `rustc` package.
> AppImage: Fix package versions and add cargo dependency

- contrib/build-wine/docker/Dockerfile
Ubuntu 21.10 (Impish) is end-of-life and no longer available on the mirrors. This patch upgrades to Ubuntu 22.04 (Jammy) which is the next LTS release.
> Wine: Update Ubuntu from impish to jammy

- electroncash/wallet.py
This PR adds a third return argument to `wallet.get_payment_status`: a list of tx hashes which were used to pay the request. It is often useful to know which transactions were involved
> get_payment_status: return list of txes relevant to invoice

- electroncash/wallet.py
This PR allows restoring wallet completely in memory, without writing to disk. The restore func needed some changes.
Also initializing i.e. CashAcct used wallet.basename(), which failed
> Allow restoring wallet in diskless mode

- electroncash/servers.json
greedyhog.mooo.com no dns since march 1 2022
fulcrum.devops.cash no answer since apr 8 2022
ec-bcn.criptolayer.net no dns since jan 18 2022
bchisbitcoin.com no answer since june 1 2022
bxdp2p6abpqt5etc.onion depreciated oct 2021
> remove offline mainnet servers

- .gitignore
- electron-cash
- electroncash/commands.py
- electroncash/daemon.py
- electroncash_gui/qt/__init__.py
- electroncash_gui/qt/main_window.py
This continues https://github.com/Electron-Cash/Electron-Cash/pull/2399, which sought to backport https://github.com/Electron-Cash/Electron-Cash/commit/9cfeadea706dbbb46b1a4ab7b38ec11a4f527669
This PR retains the commits from ecdsa and jonas-lundqvist, and also:
- Adds the prerequisite commit https://github.com/spesmilo/electrum/commit/de903103dafd46e1073d0e4de5df86e2407386bd so that these RPCs are usable from the GUI console.
- Adds back the `default_wallet` field to the `getinfo` response for maximum compatibility with JSON-RPC clients.
- Retains the daemon commands to avoid breaking changes, for now.
- qt: on GUI wallet loading or creation, sets the JSON-RPC server's command runner wallet.
> commands: getinfo and list_wallets daemon cmds to RPCs

- README.rst
I tried to run Electron Cash from source on Ubuntu 20.04 and 18.04.6 and it did not create the icons automatically
This command fixes the error:
"Cannot open file ':icons/electron-cash.svg', because: No such file or directory"
> Add instructions to compile the icons for Qt

- electroncash/wallet.py
This pull request adds a new field, tx_hashes to payment requests output
This is useful to know which transactions were used to pay an invoice.
> Add `tx_hashes` to exported payment requests

- contrib/requirements/requirements-regtest.txt
- electroncash/tests/regtest/configs/bitcoind.conf
- electroncash/tests/regtest/configs/electron-cash-config
- electroncash/tests/regtest/configs/fulcrum.conf
- electroncash/tests/regtest/docker-compose.yml
- electroncash/tests/regtest/test_daemon.py
- tox.ini
Launch BCHN and Fulcrum Docker containers and start a EC daemon that accepts RPC requests that gets verified in the test cases.
Add trivial test cases that checks the following RPC methods:
getunusedaddress
getbalance
getservers
Only enabled for Linux amd64 due to lack of test environment, will be skipped on other environments.
Fulcrum & BCHN can also also be launched in regtest mode via:
$ docker-compose -f electroncash/tests/regtest/docker-compose.yml up
And the application can connect to this network via the --regtest argument.
> Regtest via pytest

- electroncash/servers.json
I moved my node to a different hosting provider and made some DNS changes. Updating server list appropriately.
Old clients will be able to connect to "bch.ninja" until 30 days after this change is released.
> Change bch.ninja to cashnode.bch.ninja

- electroncash/paymentrequest.py
Setting an address based on a public signing key as the requestor can (and has) caused confusion where users think they can send funds. Set the key owner which is hard coded to 'BitPay, Inc.' instead.
Fix has been verified with invoice from test.bitpay.com.
Fixes #2505
> Set BitPay as requestor on jsonPayPro invoices

- electroncash/tests/test_paymentrequests.py
Verify that signature verification works on BitPay invoices. The signature check itself is kind of Mickey Mouse-ish since the keys themselves aren't verified so this rather verifies that the payment request is well formed.
> Add basic test for jsonPaymentProtocol

- .github/workflows/run-tox.yml
- README.rst
It's advised to run also on the `master` branch to avoid regression impact. This configuration now also avoids double runs when pushing to pull requests.
Also display the pipeline status of the `master` branch with the link to the workflow of the master overview to the README.rst file.
> Trigger on Master branch + Add GitHub Action badge to README

- contrib/base.sh
Do not use zero jobs during `git submodule update`, since the git interface is changed. Zero jobs are no longer accepted.
See change: https://github.com/git/git/commit/51243f9f0f6a932ea579fd6f8014b348f8c2a523
> Use a non-zero nr of jobs

- electroncash/tests/test_paymentrequests.py
For some bitpay tests a signature was trashed by setting last char to '0' but there was some cases where sig could have that. Instead flip the last bit.
Do the same thing for the digest for symmetry.
> test: Flip last bit in negative test cases

- .github/workflows/run-tox.yml
It's redundant and error prone to archive the coverage report(s) for all test jobs. Only do it for linux+python3.11.
> Only archive GH Actions artifacts once

- contrib/deterministic-build/find_restricted_dependencies.py
New release of pyinstaller (4.3) broke the script (which is used by freeze_packages.sh).
-----
Compare:
$ wget https://pypi.org/pypi/pyinstaller/4.3/json
$ cat json | jq ".info.requires_dist"
[
"setuptools",
"altgraph",
"pyinstaller-hooks-contrib (>=2020.6)",
"importlib-metadata ; python_version < \"3.8\"",
"macholib (>=1.8) ; sys_platform == \"darwin\"",
"pefile (>=2017.8.1) ; sys_platform == \"win32\"",
"pywin32-ctypes (>=0.2.0) ; sys_platform == \"win32\"",
"tinyaes (>=1.0.0) ; extra == 'encryption'",
"pytest (>=2.7.3) ; extra == 'hook_testing'",
"execnet (>=1.5.0) ; extra == 'hook_testing'",
"psutil ; extra == 'hook_testing'"
]
$ wget https://pypi.org/pypi/pyinstaller/4.2/json | jq . $ cat json | jq ".info.requires_dist"
null
$ wget https://pypi.org/pypi/qrcode/6.1/json
$ cat json | …
> contrib: fix find_restricted_dependencies for deps with version range

- electroncash_gui/qt/token_history_list.py
- electroncash_gui/qt/token_list.py
- electroncash_gui/qt/token_send.py
- Adjusted the lower panel on the send_token form so that it's adjustable while keeping the Pay To field small, using stretch factors.  If this still causes issues, I can backtrack a little to my first tweak that stops the Pay To field from being adjustable
- Set more useful initial height ratios - particularly so that the middle panel on the mint form (which will typically have the most content) is largest.
- Adjusted the top table on the Mint form so that the category ID fits on narrow views without pushing content off the right
- Dealt with a couple leftover `_("")`s
> Make bottom panel resizable. Other layout tweaks

- electroncash_gui/qt/token_send.py
- Standardized the heights and surrounding margins of the various in-table widgets
- Fixed the hover-highlight effect on table rows (visible for me only on the Dark theme)
- Simplified some conditional statements
- Make the Clear button on the minting form work
> Fix various token_send QTreeWidget layout issues

- electroncash_gui/qt/token_send.py
Rather than changing behaviour per-platform/theme, I figured out how to more precisely target the relevant widgets that need transparent backgrounds.  This is partly because I discovered that the widgets need this adjustment on both the dark and light themes for me!
> Fix transparent scrollbars

- electroncash_plugins/satochip/qt.py
The method card_verify_authenticity() verifies the authenticity of a Satochip hardware wallet.
This PR replaces self.cc with client.cc to correct a bug that crashes the application.
> Satochip plugin: patch method card_verify_authenticity() in qt.py

- electroncash/servers.json
`fulcrum.jettscythe.xyz` was missing a comma
> Servers: Fix missing comma

- contrib/build-linux/appimage/Dockerfile_ub1804
Previous versions are unavailable. This also adds a small comment explaining how to query existing package versions now that the Ubuntu package search dropped support for 18.04 (Bionic).
> AppImage: Update package versions

- contrib/build-linux/appimage/_build.sh
We need to exclude the glib libraries, otherwise we can end up using multiple incompatible versions.
We could have also included all glib libraries, but then we would have to include the full gstreamer libraries too.
See https://github.com/AppImageCommunity/pkg2appimage/pull/500#issuecomment-1057287738
> AppImage: Remove glib libraries from bundle to make QR scanner work

- electroncash/tests/regtest/docker-compose.yml
`pytest-docker` switched from `docker-compose` to `docker compose` in version 2.0.0:
https://github.com/avast/pytest-docker/releases/tag/v2.0.0
The new docker compose v2 works slightly different in some cases. In this case the path for our bind mount must be relative to the `docker-compose.yml` file.
If the build fails make sure you can run `docker compose`, if not your docker installation is too old.
> Tests: Fix docker-compose bind mount of configuration files

- .github/workflows/run-tox.yml
This updates the Python 3.12 tests to the latest RC2 version.
This also removes the exclusion of Windows that was added in https://github.com/Electron-Cash/Electron-Cash/pull/2662 because the current release candidate does not crash on startup anymore.
fixes #2673
> Tests: Update Python 3.12 to 3.12.0-rc.2, include Windows

- electroncash/secp256k1.py
To be better able to diagnose loading failures of `libsecp256k1-0.dll` this patch adds a more detailed warning print to the failure case where all tried paths and their errors are listed.
Example:
```
[secp256k1] warning: libsecp256k1 library failed to load
[secp256k1] warning: loading from libsecp256k1-0.dll failed with: <class 'FileNotFoundError'>
[secp256k1] warning: loading from H:\dev\Electron-Cash\electroncash\libsecp256k1-0.dll failed with: <class 'FileNotFoundError'>
```
> secp256k1: Improve warning message by adding path and exception details

- electroncash/plugins.py
- electroncash_gui/qt/main_window.py
I accidentally broke this in #2662, not sure how I missed this when testing :\
One of these is a backport of Electrum-ABC.
> plugins: Fix Optional Features list and External Plugin loading

- .github/workflows/run-tox.yml
This changes the Python version from `3.12.0-rc.2` to `3.12` which was recently released and we also upload the artifacts from that version.
> tests: Use Python 3.12

- electroncash_gui/qt/contact_list.py
- electroncash_gui/qt/installwizard.py
- electroncash_gui/qt/invoice_list.py
- electroncash_gui/qt/main_window.py
- electroncash_gui/qt/token_meta_edit.py
- ios/ElectronCash/electroncash_gui/ios_native/gui.py
The titles of load / save dialogs used the wrong title in various locations, this fixes it.
There were also some inconsistent strings which have been made consistent.
This also makes some previously untranlatable string translatable.
> Fix various strings that were wrong, inconsistent or not translatable

- contrib/requirements/requirements-regtest.txt
- electroncash/tests/regtest/configs/bitcoind.conf
- electroncash/tests/regtest/configs/fulcrum.conf
- electroncash/tests/regtest/docker-compose.yml
- electroncash/tests/regtest/test_rpc_misc.py
- electroncash/tests/regtest/test_rpc_payment_request.py
- electroncash/tests/regtest/util.py
The regtest tests are sometimes flaky when the machine running the test already has a port bound. To fix this we let docker choose free ports to bind on the host and get them via pytest-docker's `port_for` method.
There are also some other minor fixes in this.
> tests: improve regtest reliability

- contrib/update_test_certs
The comment for the badchain certificate was wrong, this is not a self-signed certificate, it is a certificate chain that includes a self-signed cerifiicate.
> update_test_certs: fix comment for badchain

- electroncash/base_wizard.py
- electroncash/keystore.py
- electroncash/wallet.py
- electroncash_gui/qt/main_window.py
- electroncash_gui/qt/util.py
- electroncash_gui/qt/wallet_information.py
- electroncash_plugins/fusion/fusion.py
- electroncash_plugins/fusion/qt.py
This PR adds a new wallet type `multi_xpub`, which is an "aggregate" wallet able to manage multiple `xpub`s (and/or `xprv`s, if so specified by user).  The wallet can manage any combination of multiple `xpub`/`xprv` HD master keys, and provide a unified "view" over the addresses that those master keys generate.
Creating the wallet involves the same steps as a regular single-`xpub` wallet in the wizard: "Standard wallet" -> "Use keys", then just paste multiple unique `xpub` and/or `xprv`s into the wizard and instead of a "standard" wallet you get this new aggregate wallet type.
Behind the scenes, this wallet type is somewhat similar to the MultiSig wallet in that it basically manages multiple `KeyStore` objects, except that it produces `p2pkh` addresses.
The addresses are generated by …
> Implemented a new wallet type: `multi_xpub`

- contrib/build-wine/docker/Dockerfile
https://changelogs.ubuntu.com/changelogs/pool/main/x/xorg-server/xorg-server_21.1.4-2ubuntu1.7~22.04.5/changelog
https://changelogs.ubuntu.com/changelogs/pool/main/s/samba/samba_4.15.13+dfsg-0ubuntu1.5/changelog
> build-wine: Update xvfb and winbind to latest security patch

- electroncash_gui/qt/wallet_information.py
The `PyQt5.Qt` namespace should not be used.
```
ImportError: cannot import name 'Qt' from 'PyQt5.Qt' (unknown location)
```
> Qt: Fix PyQt5 import from PyQt5.Qt instead of PyQt5.QtCore

- electroncash_plugins/trezor/clientbase.py
- electroncash_plugins/trezor/trezor.py
These changes will update the electron cash plugin so it will work with the latest trezor library.  This library is required for support of the newly released Trezor Safe 3.   In addition to updating the required and permitted versions of the library, it was necessary to edit two lines of code, because at version 0.13.0 of the library an incompatible change was made.
To use this library running from source it will be necessary to install Trezor library 0.13.8.
This can be done by pip3 install trezor 0.13.8
Testing message signing and transaction signing was made with these changes off of the released Electron Cash 4.3.1 on Ubuntu 22.04 with Python 3.10.12.  Verification worked with Trezor Model one and Trezor Model T as well as the new Trezor model 3.  For those wanting to test …
> Update Trezor plug in to work with latest Trezor library

- electroncash/commands.py
- electroncash/transaction.py
This fixes #2775 by adding `version` as an optional parameter for `Transaction.from_io` in `transaction.py` and including that parameter in the `serialize` command in `commands.py`.
> Adding optional version parameter for serialization via Transaction.from_io

- contrib/deterministic-build/requirements-build-wine.txt
Without this the "Add plugins" button and likely other file selection dialogs would crash the app.
> build: update pyinstaller-hooks-contrib to version 2024.1

- contrib/build-linux/appimage/Dockerfile_ub2004
- contrib/build-linux/appimage/_build.sh
This also uses a patched version of cryptography that passes `-fmacro-prefix-map` to the compiler.
fixes #2807
> build: Fix AppImage reproducibility by using rusts trim-paths

- contrib/build-wine/docker/Dockerfile
apt-key is deprecated and keys should be specified per source instead of for all sources.
> build: remove deprecated apt-key for winehq key

- .github/workflows/run-tox.yml
Only run all supported version on the linux version. Only run the packaged version on macos/windows.
> Exclude python versions in GitHub Actions

- .github/workflows/audit.yml
GHSA-jjg7-2v4v-x38h is a minor issue that will be fixed when idna is bumped the next time.
> audit: Silence idna vulnerability

- electroncash/tests/regtest/docker-compose.yml
bitcoin-cash-node:27.0.0
fulcrum:v1.10.0
> regtest: Bump docker containers

- electroncash/tor/controller.py
The message reader would exit early on empty / undecodable messages which would cause the tor process to get stuck. This makes it exit only when readline fails.
Using this it is possible to start tor with debug logging.
> tor: fix message reader getting stuck

- electron-cash
- electroncash/commands.py
This enhancement allows getting raw transactions from local wallet files.  As this only works when the software is not already running, I check for server before adjusting the command requirements.  As any transaction not in the wallet will otherwise fall back to the non-existent network under these conditions, I added exception handling similar to that which already existed for unknown transactions.
> Enable offline extraction of wallet transactions

- electron-cash
This is a bugfix.  The previous version of this statement would not evaluate correctly, so commands needing passwords would fail returning the following if there was no daemon/gui:
```
Traceback (most recent call last):
File "/tmp/.mount_ElectrnnTI9Z/usr/bin/electron-cash", line 589, in <module>
main()
File "/tmp/.mount_ElectrnnTI9Z/usr/bin/electron-cash", line 581, in main
result = run_cmdline(config, config_options, cmdname)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/.mount_ElectrnnTI9Z/usr/bin/electron-cash", line 427, in run_cmdline
result = run_offline_command(config, config_options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/.mount_ElectrnnTI9Z/usr/bin/electron-cash", line 310, in run_offline_command
storage.decrypt(password)
File …
```
> Correct if statement for commands needing password

- tox.ini
This way tox can be running on its own on newer python version
> Add python3.12 to tox.ini

- contrib/build-linux/appimage/Dockerfile_ub2004
- contrib/build-linux/appimage/_build.sh
This is to make `zxing-cpp` build again. The root cause is an issue in `pybind11`, see:
* https://github.com/pybind/pybind11/releases/tag/v2.13.1
* https://github.com/pybind/pybind11/issues/5201
* https://github.com/pybind/pybind11/pull/5205
* https://github.com/zxing-cpp/zxing-cpp/issues/803
The currently used `mksquashfs` does not build with gcc 10 and the source has not been updated for 5 years. We switch to the Ubuntu package instead of another upstream.
> build: switch AppImage to gcc 10 and remove mksquashfs build

- contrib/build-wine/_build.sh
We need to install `exe.msi` before `dev.msi` or there will be a stack overflow in wine.
> build: fix python dev.msi installation in wine

- contrib/make_locale
- electroncash/wallet.py
Using a seperate repo as the source for translation files allows us to manage which specific files are active and live on the build system.
A couple fixes for nits on the recent Android CashTokens PR are included.
> Pull translations from Github instead of Crowdin

- contrib/make_locale
Although the previous PR fixed the generation of the *.mo files, these were not being picked up at runtime when running from source, since the files were stored in the wrong location. This PR fixes this by ensuring the translations files appear in `electroncash/locale`.  NB: The AppImage builds were nevertheless working correctly because there is a different shell script that does this work for them.
> Fix translations when running from source

- android/Dockerfile
- contrib/make_locale
This is on top of #2904 
Now that we are using `contrib/electrum-locale` as the source for translation files by default (rather than straight from Crowdin), this PR makes these files available to the Android build process
> Update apk translations source

- android/app/src/main/java/org/electroncash/electroncash3/Requests.kt
- android/app/src/main/java/org/electroncash/electroncash3/TokenTransactions.kt
This PR fixes the issue on the Android wallet where users are unable to open the receive dialog on watching-only wallets. It should only ever have been the send functionality disabled for such wallets, not the receive functionality too.
This PR also fixes a related problem where the app would crash when trying to open the send dialog from the Token Transactions screen on a watching only wallet.  It should now correctly raise the "This wallet is watching-only" warning.
Closes #2613, closes #2941, closes #2934, closes #2926, closes #2925, closes #2032
> [android] Enable receive dialog and fix send warning on watching-only wallets

- electroncash/commands.py
- electroncash/consolidate.py
- electroncash/tests/test_consolidate.py
- electroncash/transaction.py
Adds the basics for the consolidate tool on the CLI level.  Can be used as a basis for the gui implementation if desired at a later time. Can also be expanded to include more functionality in terms of the command parameters.  To fully test, it should be tested on a wallet with hundreds of UTXO on the same address so that it creates multiple transactions.  Currently, it has been only tested for a wallet with a single consolidate transaction.  To test, enter the command consolidatecoins("your-bch-address") in the command console, then copy the raw transaction and paste into the wallet using the load transaction from text tool, then sign the transaction and broadcast.
> Consolidate tool CLI 

- contrib/deterministic-build/requirements-hw.txt
- contrib/requirements/requirements-hw.txt
The keepkey Python library stopped working with protobuf >= 5. This updates the dependency to a fixed version.
See https://github.com/keepkey/python-keepkey/issues/146
Fixes #2995
> keepkey: fix for protobuf versions >= 5

- setup.py
These are needed to regenerated the compiled protobuf files in case the system protobuf library is not compatible with the compiled files we bunlde.
> build: include proto files in source distribution

- contrib/build-linux/appimage/Dockerfile_ub2004
```
1 warning found (use docker --debug to expand):
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 7)
```
Changed to use the equals sign.
> build: Fix docker legacy env warning
